// Comprehensive Taiwan stock ticker → name lookup map
// Covers: 0050 (台灣50), 0051 (中型100) constituents, popular ETFs, and other commonly traded stocks
// Used for auto-complete when adding stock tags; also exports scanStocks and lookupStock for article detection
import { categories } from "./stock-list";

export const stockLookup: Record<string, string> = {
  // ─── ETF ────────────────────────────────────────────────
  "0050": "元大台灣50",
  "0051": "元大中型100",
  "0052": "富邦科技",
  "0053": "元大電子",
  "0055": "元大MSCI金融",
  "0056": "元大高股息",
  "006205": "富邦上証",
  "006208": "富邦台50",
  "00690": "兆豐藍籌30",
  "00692": "富邦公司治理",
  "00701": "國泰股利精選30",
  "00713": "元大台灣高息低波",
  "00733": "富邦臺灣中小",
  "00850": "元大臺灣ESG永續",
  "00878": "國泰永續高股息",
  "00881": "國泰台灣5G+",
  "00882": "中信中國高股息",
  "00885": "富邦越南",
  "00891": "中信關鍵半導體",
  "00892": "富邦台灣半導體",
  "00893": "國泰智能電動車",
  "00894": "中信小資高價30",
  "00895": "富邦未來車",
  "00896": "中信綠能及電動車",
  "00900": "富邦特選高股息30",
  "00919": "群益台灣精選高息",
  "00929": "復華台灣科技優息",
  "00934": "中信成長高股息",
  "00935": "野村台灣新科技50",
  "00936": "台新臺灣永續高息中小型",
  "00939": "統一台灣高息動能",
  "00940": "元大台灣價值高息",
  "00941": "中信上游半導體",

  // ─── 0050 成分股（台灣50）────────────────────────────────
  "1101": "台泥",
  "1216": "統一",
  "1301": "台塑",
  "1303": "南亞",
  "1326": "台化",
  "2002": "中鋼",
  "2207": "和泰車",
  "2301": "光寶科",
  "2303": "聯電",
  "2308": "台達電",
  "2317": "鴻海",
  "2327": "國巨",
  "2330": "台積電",
  "2345": "智邦",
  "2357": "華碩",
  "2379": "瑞昱",
  "2382": "廣達",
  "2395": "研華",
  "2412": "中華電",
  "2454": "聯發科",
  "2474": "可成",
  "2603": "長榮",
  "2880": "華南金",
  "2881": "富邦金",
  "2882": "國泰金",
  "2883": "開發金",
  "2884": "玉山金",
  "2885": "元大金",
  "2886": "兆豐金",
  "2887": "台新金",
  "2890": "永豐金",
  "2891": "中信金",
  "2892": "第一金",
  "2912": "統一超",
  "3008": "大立光",
  "3034": "聯詠",
  "3037": "欣興",
  "3045": "台灣大",
  "3231": "緯創",
  "3661": "世芯-KY",
  "3711": "日月光投控",
  "4904": "遠傳",
  "4938": "和碩",
  "5876": "上海商銀",
  "5880": "合庫金",
  "6415": "矽力-KY",
  "6446": "藥華藥",
  "6505": "台塑化",
  "6669": "緯穎",

  // ─── 0051 成分股（中型100）及其他上市櫃常見個股 ──────────
  "1102": "亞泥",
  "1227": "佳格",
  "1229": "聯華",
  "1304": "台聚",
  "1314": "中石化",
  "1402": "遠東新",
  "1434": "福懋",
  "1440": "南紡",
  "1476": "儒鴻",
  "1477": "聚陽",
  "1504": "東元",
  "1560": "中砂",
  "1590": "亞德客-KY",
  "1605": "華新",
  "1722": "台肥",
  "1727": "中華化",
  "1802": "台玻",
  "1907": "永豐餘",
  "2006": "東鋼",
  "2014": "中鴻",
  "2015": "豐興",
  "2049": "上銀",
  "2059": "川湖",
  "2101": "南港",
  "2105": "正新",
  "2201": "裕隆",
  "2204": "中華",
  "2227": "裕日車",
  "2312": "金寶",
  "2313": "華通",
  "2324": "仁寶",
  "2337": "旺宏",
  "2344": "華邦電",
  "2347": "聯強",
  "2352": "佳世達",
  "2353": "宏碁",
  "2356": "英業達",
  "2360": "致茂",
  "2376": "技嘉",
  "2377": "微星",
  "2383": "台光電",
  "2385": "群光",
  "2388": "威盛",
  "2392": "正崴",
  "2404": "漢唐",
  "2408": "南亞科",
  "2449": "京元電子",
  "2451": "創見",
  "2455": "全新",
  "2458": "義隆",
  "2467": "志聖",
  "2492": "華新科",
  "2498": "宏達電",
  "2542": "興富發",
  "2545": "皇翔",
  "2548": "華固",
  "2606": "裕民",
  "2609": "陽明",
  "2610": "華航",
  "2615": "萬海",
  "2618": "長榮航",
  "2633": "台灣高鐵",
  "2634": "漢翔",
  "2645": "長榮航太",
  "2801": "彰銀",
  "2809": "京城銀",
  "2812": "台中銀",
  "2834": "臺企銀",
  "2838": "聯邦銀",
  "2845": "遠東銀",
  "2855": "統一證",
  "2867": "三商壽",
  "2888": "新光金",
  "2889": "國票金",
  "2903": "遠百",
  "2904": "匯僑-KY",
  "2915": "潤泰全",
  "3003": "健鼎",
  "3004": "豐達科",
  "3006": "晶豪科",
  "3017": "奇鋐",
  "3023": "信邦",
  "3035": "智原",
  "3036": "文曄",
  "3044": "健鼎",
  "3049": "和鑫",
  "3058": "立德",
  "3081": "聯亞",
  "3105": "穩懋",
  "3131": "弘塑",
  "3189": "景碩",
  "3260": "威剛",
  "3296": "勝德",
  "3324": "雙鴻",
  "3357": "臺慶科",
  "3376": "新日興",
  "3443": "創意",
  "3450": "聯鈞",
  "3481": "群創",
  "3515": "華擎",
  "3529": "力旺",
  "3533": "嘉澤",
  "3563": "牧德",
  "3583": "辛耘",
  "3587": "閎康",
  "3588": "通嘉",
  "3596": "智易",
  "3615": "安可",
  "3617": "碩天",
  "3653": "健策",
  "3665": "貿聯-KY",
  "3680": "家登",
  "3686": "達能",
  "3690": "美磊",
  "3694": "海華",
  "3702": "大聯大",
  "3706": "神達",
  "3715": "定穎投控",
  "4142": "國光生",
  "4552": "力達-KY",
  "4743": "合一",
  "4746": "台耀",
  "4906": "正文",
  "4919": "新唐",
  "4927": "泰鼎-KY",
  "4958": "臻鼎-KY",
  "4961": "天鈺",
  "4966": "譜瑞-KY",
  "4967": "十銓",
  "5222": "全訊",
  "5234": "達興材料",
  "5269": "祥碩",
  "5274": "信驊",
  "5285": "界霖",
  "5306": "桂盟",
  "5347": "世界",
  "5388": "中磊",
  "5425": "台半",
  "5469": "瀚宇博",
  "5483": "中美晶",
  "5871": "中租-KY",
  "5903": "全家",
  "5904": "寶雅",
  "6005": "群益證",
  "6116": "彩晶",
  "6120": "達運",
  "6139": "亞翔",
  "6176": "瑞儀",
  "6191": "精成科",
  "6196": "帆宣",
  "6197": "佳必琪",
  "6213": "聯茂",
  "6223": "旺矽",
  "6230": "超眾",
  "6239": "力成",
  "6257": "矽格",
  "6269": "台郡",
  "6271": "同欣電",
  "6274": "台燿",
  "6278": "台表科",
  "6285": "啟碁",
  "6414": "樺漢",
  "6431": "光麗-KY",
  "6438": "迅得",
  "6449": "鈺邦",
  "6451": "訊芯-KY",
  "6456": "GIS-KY",
  "6488": "環球晶",
  "6504": "南六",
  "6510": "精測",
  "6515": "穎崴",
  "6523": "達爾膚",
  "6531": "愛普",
  "6533": "晶心科",
  "6547": "高端疫苗",
  "6552": "易華電",
  "6573": "虹揚-KY",
  "6581": "鋼聯",
  "6584": "南俊國際",
  "6592": "和潤企業",
  "6605": "帝寶",
  "6625": "必應",
  "6643": "戎美-KY",
  "6664": "群翊",
  "6666": "羅麗芬-KY",
  "6668": "中揚光",
  "6670": "復盛應用",
  "6672": "騰輝電子-KY",
  "6719": "力智",
  "6752": "未秧-KY",
  "6753": "龍德造船",
  "6756": "威鋒電子",
  "6768": "志強-KY",
  "6770": "力積電",
  "6781": "AES-KY",
  "6789": "采鈺",
  "6805": "富世達",
  "6826": "和淞",
  "6890": "來億-KY",
  "6894": "衛司特",
  "6937": "天虹",
  "7822": "倍利科",
  "7853": "政美應用",
  "8008": "建興電",
  "8016": "矽創",
  "8027": "鈦昇",
  "8046": "南電",
  "8069": "元太",
  "8086": "宏捷科",
  "8112": "至上",
  "8150": "南茂",
  "8210": "勤誠",
  "8213": "志超",
  "8255": "朋程",
  "8261": "富鼎",
  "8271": "宇瞻",
  "8299": "群聯",
  "8341": "日友",
  "8358": "金居",
  "8454": "富邦媒",
  "8462": "柏文",
  "8464": "億豐",
  "8936": "國統",
  "9802": "鈺齊-KY",
  "9904": "寶成",
  "9910": "豐泰",
  "9914": "美利達",
  "9921": "巨大",
  "9927": "泰銘",
  "9933": "中鼎",
  "9938": "百和",
  "9939": "宏全",
  "9941": "裕融",
  "9945": "潤泰新",
  "4991": "環宇-KY",
  "1815": "富喬",
  "2342": "茂矽",
  "2472": "立隆電",
  "3402": "漢科",
  "4722": "國精化",
  "6147": "頎邦",
  "6175": "立敦",
  "4764": "雙鍵",
  "5340": "建榮",
  "5475": "德宏",

  // ─── 美國 ETF ──────────────────────────────────────────
  "SPY": "SPDR S&P 500 ETF",
  "VOO": "Vanguard S&P 500 ETF",
  "IVV": "iShares Core S&P 500 ETF",
  "QQQ": "Invesco QQQ (Nasdaq 100)",
  "QQQM": "Invesco Nasdaq 100 ETF",
  "SOXX": "iShares Semiconductor ETF",
  "SMH": "VanEck Semiconductor ETF",
  "VTI": "Vanguard Total Stock Market ETF",
  "VGT": "Vanguard IT ETF",
  "XLK": "Technology Select Sector SPDR",
  "XLF": "Financial Select Sector SPDR",
  "XLE": "Energy Select Sector SPDR",
  "XLV": "Health Care Select Sector SPDR",
  "XLI": "Industrial Select Sector SPDR",
  "XLP": "Consumer Staples Select Sector SPDR",
  "XLY": "Consumer Discretionary Select SPDR",
  "ARKK": "ARK Innovation ETF",
  "DIA": "SPDR Dow Jones Industrial ETF",
  "IWM": "iShares Russell 2000 ETF",
  "VT": "Vanguard Total World Stock ETF",
  "VXUS": "Vanguard Total Intl Stock ETF",
  "EEM": "iShares MSCI Emerging Markets ETF",

  // ─── 美國 VOO/S&P 500 + QQQ/Nasdaq 100 + SOXX 成分股 ──
  // Top mega-cap
  "AAPL": "Apple",
  "MSFT": "Microsoft",
  "AMZN": "Amazon",
  "NVDA": "NVIDIA",
  "GOOG": "Alphabet",
  "8053.T": "Sumitomo",
  "6944": "兆聯實業",
  "7703": "銳澤",
  "7631": "聚賢研發-創",
  "6187": "萬潤",
  "6640": "均華",
  "META": "Meta",
  "BRK.B": "Berkshire Hathaway",
  "TSLA": "Tesla",
  "UNH": "UnitedHealth",
  "XOM": "ExxonMobil",
  "JNJ": "Johnson & Johnson",
  "JPM": "JPMorgan Chase",
  "V": "Visa",
  "PG": "Procter & Gamble",
  "MA": "Mastercard",
  "AVGO": "Broadcom",
  "HD": "Home Depot",
  "CVX": "Chevron",
  "MRK": "Merck",
  "LLY": "Eli Lilly",
  "ABBV": "AbbVie",
  "PEP": "PepsiCo",
  "KO": "Coca-Cola",
  "COST": "Costco",
  "BAC": "Bank of America",
  "ADBE": "Adobe",
  "WMT": "Walmart",
  "MCD": "McDonald's",
  "CRM": "Salesforce",
  "CSCO": "Cisco",
  "TMO": "Thermo Fisher",
  "ACN": "Accenture",
  "ABT": "Abbott",
  "NFLX": "Netflix",
  "DHR": "Danaher",
  "LIN": "Linde",
  "TXN": "Texas Instruments",
  "CMCSA": "Comcast",
  "NKE": "Nike",
  "PM": "Philip Morris",
  "ORCL": "Oracle",
  // Semiconductor / SOXX
  "AMD": "AMD",
  "INTC": "Intel",
  "MU": "Micron",
  "QCOM": "Qualcomm",
  "AMAT": "Applied Materials",
  "LRCX": "Lam Research",
  "KLAC": "KLA",
  "ASML": "ASML",
  "MRVL": "Marvell",
  "ON": "ON Semiconductor",
  "SNPS": "Synopsys",
  "CDNS": "Cadence",
  "ARM": "Arm Holdings",
  "TSM": "TSMC (ADR)",
  "NXPI": "NXP Semiconductors",
  "ADI": "Analog Devices",
  "MPWR": "Monolithic Power Systems",
  "SWKS": "Skyworks Solutions",
  "QRVO": "Qorvo",
  "MCHP": "Microchip Technology",
  "TER": "Teradyne",
  "ENTG": "Entegris",
  "MKSI": "MKS Instruments",
  "LSCC": "Lattice Semiconductor",
  "WOLF": "Wolfspeed",
  "ACLS": "Axcelis Technologies",
  "CRUS": "Cirrus Logic",
  "SLAB": "Silicon Labs",
  "DIOD": "Diodes",
  "MTSI": "MACOM Technology",
  "SITM": "SiTime",
  "RMBS": "Rambus",
  "COHR": "Coherent",
  "LITE": "Lumentum",
  "AMKR": "Amkor Technology",
  "FORM": "FormFactor",
  "ONTO": "Onto Innovation",
  "POWI": "Power Integrations",
  "ALGM": "Allegro MicroSystems",
  "GFS": "GlobalFoundries",
  "UMC": "UMC (ADR)",
  "ASX": "ASE Technology (ADR)",
  "STM": "STMicroelectronics",
  "IFX": "Infineon",
  // Tech / Software / Cloud (QQQ)
  "DELL": "Dell",
  "HPE": "HP Enterprise",
  "HPQ": "HP Inc",
  "SMCI": "Super Micro Computer",
  "PLTR": "Palantir",
  "SNOW": "Snowflake",
  "CRWD": "CrowdStrike",
  "PANW": "Palo Alto Networks",
  "ABNB": "Airbnb",
  "UBER": "Uber",
  "SQ": "Block (Square)",
  "SHOP": "Shopify",
  "COIN": "Coinbase",
  "SOFI": "SoFi",
  "NOW": "ServiceNow",
  "INTU": "Intuit",
  "WDAY": "Workday",
  "ZS": "Zscaler",
  "DDOG": "Datadog",
  "NET": "Cloudflare",
  "MDB": "MongoDB",
  "TEAM": "Atlassian",
  "VEEV": "Veeva Systems",
  "FTNT": "Fortinet",
  "ANSS": "Ansys",
  "TTD": "The Trade Desk",
  "DASH": "DoorDash",
  "MELI": "MercadoLibre",
  "SE": "Sea Limited",
  "BKNG": "Booking Holdings",
  "CPRT": "Copart",
  "MNST": "Monster Beverage",
  "ADP": "ADP",
  "PAYX": "Paychex",
  "CTAS": "Cintas",
  "ODFL": "Old Dominion Freight",
  "FAST": "Fastenal",
  "EA": "Electronic Arts",
  "TTWO": "Take-Two Interactive",
  "ATVI": "Activision Blizzard",
  "ROKU": "Roku",
  "ZM": "Zoom Video",
  "DOCU": "DocuSign",
  "OKTA": "Okta",
  "SPLK": "Splunk",
  "PINS": "Pinterest",
  "SNAP": "Snap",
  "LYFT": "Lyft",
  "RBLX": "Roblox",
  "U": "Unity Software",
  "PATH": "UiPath",
  "CFLT": "Confluent",
  "BILL": "Bill Holdings",
  "HUBS": "HubSpot",
  "TWLO": "Twilio",
  // EV / Automotive
  "RIVN": "Rivian",
  "LCID": "Lucid",
  "NIO": "NIO",
  "XPEV": "XPeng",
  "LI": "Li Auto",
  "GM": "General Motors",
  "F": "Ford Motor",
  "TM": "Toyota Motor (ADR)",
  "HMC": "Honda Motor (ADR)",
  // Aerospace & Defense
  "BA": "Boeing",
  "LMT": "Lockheed Martin",
  "RTX": "RTX (Raytheon)",
  "GE": "GE Aerospace",
  "NOC": "Northrop Grumman",
  "GD": "General Dynamics",
  "HII": "Huntington Ingalls",
  "LHX": "L3Harris Technologies",
  "TDG": "TransDigm",
  // Industrials
  "CAT": "Caterpillar",
  "DE": "Deere & Company",
  "HON": "Honeywell",
  "UNP": "Union Pacific",
  "UPS": "UPS",
  "FDX": "FedEx",
  "MMM": "3M",
  "EMR": "Emerson Electric",
  "ETN": "Eaton",
  "ITW": "Illinois Tool Works",
  "ROK": "Rockwell Automation",
  "PH": "Parker-Hannifin",
  "IR": "Ingersoll Rand",
  "AME": "Ametek",
  "GWW": "W.W. Grainger",
  "SHW": "Sherwin-Williams",
  "APD": "Air Products",
  "ECL": "Ecolab",
  "DD": "DuPont",
  "DOW": "Dow Inc",
  "PPG": "PPG Industries",
  "FCX": "Freeport-McMoRan",
  "NEM": "Newmont",
  // Entertainment / Media
  "DIS": "Walt Disney",
  "PARA": "Paramount Global",
  "WBD": "Warner Bros Discovery",
  "FOX": "Fox Corp",
  // Financials
  "PYPL": "PayPal",
  "GS": "Goldman Sachs",
  "MS": "Morgan Stanley",
  "C": "Citigroup",
  "WFC": "Wells Fargo",
  "SCHW": "Charles Schwab",
  "BLK": "BlackRock",
  "AXP": "American Express",
  "SPGI": "S&P Global",
  "ICE": "Intercontinental Exchange",
  "CME": "CME Group",
  "MCO": "Moody's",
  "MSCI": "MSCI",
  "AON": "Aon",
  "MMC": "Marsh & McLennan",
  "AIG": "AIG",
  "PRU": "Prudential Financial",
  "MET": "MetLife",
  "TRV": "Travelers",
  "CB": "Chubb",
  "AFL": "Aflac",
  "ALL": "Allstate",
  "PGR": "Progressive",
  "USB": "U.S. Bancorp",
  "PNC": "PNC Financial",
  "TFC": "Truist Financial",
  "COF": "Capital One",
  "FIS": "Fidelity National Info",
  "FISV": "Fiserv",
  // Healthcare / Biotech / Pharma
  "PFE": "Pfizer",
  "BMY": "Bristol-Myers Squibb",
  "AMGN": "Amgen",
  "GILD": "Gilead Sciences",
  "ISRG": "Intuitive Surgical",
  "MDT": "Medtronic",
  "SYK": "Stryker",
  "REGN": "Regeneron",
  "VRTX": "Vertex Pharmaceuticals",
  "BSX": "Boston Scientific",
  "ZBH": "Zimmer Biomet",
  "EW": "Edwards Lifesciences",
  "DXCM": "DexCom",
  "IDXX": "Idexx Laboratories",
  "IQV": "IQVIA",
  "A": "Agilent Technologies",
  "BDX": "Becton Dickinson",
  "BAX": "Baxter International",
  "BIIB": "Biogen",
  "MRNA": "Moderna",
  "ILMN": "Illumina",
  "HOLX": "Hologic",
  "ALGN": "Align Technology",
  "TECH": "Bio-Techne",
  // Consumer / Retail
  "SBUX": "Starbucks",
  "TGT": "Target",
  "LOW": "Lowe's",
  "TJX": "TJX Companies",
  "ROST": "Ross Stores",
  "DG": "Dollar General",
  "DLTR": "Dollar Tree",
  "ORLY": "O'Reilly Automotive",
  "AZO": "AutoZone",
  "CMG": "Chipotle",
  "YUM": "Yum! Brands",
  "DKNG": "DraftKings",
  "MAR": "Marriott",
  "HLT": "Hilton",
  "RCL": "Royal Caribbean",
  "LVS": "Las Vegas Sands",
  // Consumer Staples
  "CL": "Colgate-Palmolive",
  "KMB": "Kimberly-Clark",
  "GIS": "General Mills",
  "K": "Kellanova",
  "HSY": "Hershey",
  "MDLZ": "Mondelez",
  "KHC": "Kraft Heinz",
  "STZ": "Constellation Brands",
  "MO": "Altria",
  "EL": "Estee Lauder",
  // Telecom / Utilities
  "T": "AT&T",
  "VZ": "Verizon",
  "TMUS": "T-Mobile US",
  "CHTR": "Charter Communications",
  "NEE": "NextEra Energy",
  "DUK": "Duke Energy",
  "SO": "Southern Company",
  "D": "Dominion Energy",
  "AEP": "American Electric Power",
  "SRE": "Sempra",
  // Energy
  "COP": "ConocoPhillips",
  "EOG": "EOG Resources",
  "SLB": "Schlumberger",
  "MPC": "Marathon Petroleum",
  "PSX": "Phillips 66",
  "VLO": "Valero Energy",
  "OXY": "Occidental Petroleum",
  "KMI": "Kinder Morgan",
  "WMB": "Williams Companies",
  "HAL": "Halliburton",
  // Real Estate
  "AMT": "American Tower",
  "PLD": "Prologis",
  "CCI": "Crown Castle",
  "EQIX": "Equinix",
  "SPG": "Simon Property Group",
  "PSA": "Public Storage",
  "O": "Realty Income",
  "DLR": "Digital Realty",
  "WELL": "Welltower",
  "AVB": "AvalonBay",
  // Optical / Photonics
  "AAOI": "Applied Optoelectronics",

  // ─── 韓國 KOSPI 50 主要成分股 ─────────────────────────
  "005930.KS": "Samsung",
  "000660.KS": "SK Hynix",
  "005935.KS": "Samsung Electronics Pref",
  "005380.KS": "Hyundai Motor",
  "000270.KS": "Kia",
  "051910.KS": "LG Chem",
  "006400.KS": "Samsung SDI",
  "035420.KS": "Naver",
  "035720.KS": "Kakao",
  "068270.KS": "Celltrion",
  "105560.KS": "KB Financial",
  "055550.KS": "Shinhan Financial",
  "086790.KS": "Hana Financial",
  "316140.KS": "Woori Financial",
  "003670.KS": "Posco Holdings",
  "034730.KS": "SK",
  "017670.KS": "SK Telecom",
  "030200.KS": "KT",
  "032830.KS": "Samsung Life",
  "066570.KS": "LG Electronics",
  "003550.KS": "LG",
  "373220.KS": "LG Energy Solution",
  "012330.KS": "Hyundai Mobis",
  "009150.KS": "Samsung Electro-Mechanics",
  "028260.KS": "Samsung C&T",
  "034020.KS": "Doosan Enerbility",
  "010130.KS": "Korea Zinc",
  "010950.KS": "S-Oil",
  "096770.KS": "SK Innovation",
  "011200.KS": "HMM",
  "036570.KS": "NCsoft",
  "259960.KS": "Krafton",
  "018260.KS": "Samsung SDS",
  "352820.KS": "Hybe",
  "011170.KS": "Lotte Chemical",
  "047050.KS": "Posco International",
  "402340.KS": "SK Square",
  "003490.KS": "Korean Air",
  "000810.KS": "Samsung Fire & Marine",
  "000157.KS": "斗山(Doosan)",

  // ─── 中國 A 股 ──────────────────────────────────────────
  "688183.SS": "生益電子",
  "300395.SZ": "菲利華",

  // ─── 日本 Nikkei 225 主要成分股 ────────────────────────
  "7203.T": "Toyota Motor",
  "6758.T": "Sony Group",
  "6861.T": "Keyence",
  "8306.T": "MUFG",
  "9432.T": "NTT",
  "9984.T": "SoftBank Group",
  "6501.T": "Hitachi",
  "8035.T": "Tokyo Electron",
  "4063.T": "Shin-Etsu Chemical",
  "6902.T": "Denso",
  "7741.T": "HOYA",
  "4519.T": "Chugai Pharmaceutical",
  "6098.T": "Recruit Holdings",
  "7267.T": "Honda Motor",
  "6954.T": "Fanuc",
  "4568.T": "Daiichi Sankyo",
  "6857.T": "Advantest",
  "9433.T": "KDDI",
  "8058.T": "Mitsubishi Corp",
  "8031.T": "Mitsui & Co",
  "9983.T": "Fast Retailing",
  "4502.T": "Takeda Pharmaceutical",
  "7974.T": "Nintendo",
  "6723.T": "Renesas Electronics",
  "6762.T": "TDK",
  "6981.T": "Murata Manufacturing",
  "4062.T": "Ibiden",
  "7751.T": "Canon",
  "6367.T": "Daikin Industries",
  "6971.T": "Kyocera",
  "3382.T": "Seven & i Holdings",
  "2914.T": "Japan Tobacco",
  "4661.T": "Oriental Land",
  "5108.T": "Bridgestone",
  "7269.T": "Suzuki Motor",
  "7270.T": "Subaru",
  "2802.T": "Ajinomoto",
  "4901.T": "Fujifilm",
  "6301.T": "Komatsu",
  "6594.T": "Nidec",
  "7832.T": "Bandai Namco",
  "9434.T": "SoftBank Corp",
  "4543.T": "Terumo",
  "9613.T": "NTT Data",
  "6503.T": "Mitsubishi Electric",
  "7011.T": "Mitsubishi Heavy Industries",
  "8001.T": "Itochu",
  "8002.T": "Marubeni",
  "6146.T": "Disco",
  "6920.T": "Lasertec",
  "6526.T": "Socionext",
  "4755.T": "Rakuten Group",
  "6752.T": "Panasonic",
  "2413.T": "M3",
  "4307.T": "Nomura Research Institute",
  "6273.T": "SMC",
  "7735.T": "Screen Holdings",
  "3407.T": "旭化成(Asahi Kasei)",
  "3110.T": "日東紡(Nittobo)",
  "1899.T": "福田(Fukuda)",
  "5706.T": "三井金屬(Mitsui Kinzoku)",
  "5801.T": "古河電工(Furukawa)",
  "4004.T": "昭和電工(Resonac)",
  "4182.T": "三菱瓦斯化學(MGC)",
  "285A.T": "鎧俠(Kioxia)",
  "5201.T": "AGC",
  "7733.T": "Olympus",
  "8766.T": "Tokio Marine",
  "8411.T": "Mizuho Financial",
  "8316.T": "SMFG",

  // ─── 沙烏地 ──────────────────────────────────────────────
  "2010.SR": "沙特基礎工業(SABIC)",
};

// ─────────────────────────────────────────────────────────
// Scan / detection layer (previously stock-scan.ts)
// ─────────────────────────────────────────────────────────

export type ScanStock = {
  ticker: string;
  name: string;
  aliases?: string[];
};

// Aliases for category stocks + extra stocks used for article auto-detection and highlighting.
export const stockAliases: Record<string, string[]> = {
  // ─── IC設計 ──────────────────────────────────────────────
  "2379": ["Realtek"],
  "2454": ["MediaTek"],
  "5274": ["Aspeed"],
  // ─── 晶圓代工 ────────────────────────────────────────────
  "2303": ["UMC"],
  "2330": ["TSMC", "台積"],
  "5347": ["VIS", "世界先進"],
  // ─── 半導體封測 ──────────────────────────────────────────
  "3711": ["ASE", "日月光投控"],
  "6239": ["PTI"],
  "6257": ["Sigurd"],
  // ─── 半導體耗材 ──────────────────────────────────────────
  "1560": ["KINIK"],
  "1727": ["中華化學"],
  "3680": ["Gudeng"],
  "6488": ["GlobalWafers"],
  // ─── III-V族 ─────────────────────────────────────────────
  "4991": ["環宇"],
  // ─── 記憶體 ──────────────────────────────────────────────
  "2337": ["Macronix", "MXIC"],
  "2344": ["Winbond"],
  "2408": ["Nanya", "南亞科技"],
  "3260": ["ADATA"],
  "6531": ["Ap Memory", "ApMemory"],
  "8299": ["Phison"],
  // ─── 品牌/ODM ────────────────────────────────────────────
  "2317": ["Foxconn", "Hon Hai"],
  "2382": ["Quanta"],
  // ─── 電子零組件 ──────────────────────────────────────────
  "2301": ["Lite-On", "光寶"],
  "2308": ["Delta", "台達"],
  "3017": ["Asia Vital", "AVC"],
  // ─── PCB ─────────────────────────────────────────────────
  "2313": ["Compeq"],
  "3037": ["Unimicron"],
  "3715": ["定穎"],
  "4958": ["臻鼎", "ZDT"],
  "6191": ["GCE"],
  // ─── 車用零組件 ──────────────────────────────────────────
  "6271": ["Tong Hsing"],
  "8255": ["PanJit"],
  // ─── 功率元件 ────────────────────────────────────────────
  "5425": ["TSC"],
  // ─── 銅箔基板 ────────────────────────────────────────────
  "2383": ["EMC", "台光"],
  "6274": ["Taiflex"],
  "8358": ["Co-Tech"],
  // ─── 雲端/CSP ───────────────────────────────────────────
  "AMZN": ["AWS"],
  "MSFT": ["Azure"],
  "GOOG": ["Google", "GCP"],
  // ─── 其他美股 ────────────────────────────────────────────
  "STM": ["STMicro"],
  // ─── 日股 ────────────────────────────────────────────────
  "3407.T": ["旭化成", "Asahi Kasei", "Asahi"],
  "3110.T": ["日東紡", "Nittobo"],
  "1899.T": ["福田", "Fukuda"],
  "5706.T": ["三井金屬", "Mitsui Kinzoku"],
  "5801.T": ["古河電工", "Furukawa"],
  "4004.T": ["昭和電工", "Resonac"],
  "4182.T": ["三菱瓦斯化學", "MGC"],
  "285A.T": ["鎧俠", "Kioxia"],
  // ─── 韓股 ────────────────────────────────────────────────
  "000157.KS": ["斗山", "Doosan"],
  // ─── 沙烏地 ──────────────────────────────────────────────
  "2010.SR": ["沙特基礎工業", "SABIC", "Sabic"],
};

// Extra stocks for detection only — not shown on /stock page.
const extraStockTickers = new Set([
  "AMZN", "MSFT", "GOOG", "STM", "7631",
  "3407.T", "3110.T", "1899.T", "5706.T", "5801.T", "4004.T", "4182.T", "285A.T",
  "000157.KS", "2010.SR",
]);

// All stocks for article auto-detection and text highlighting.
// = category stocks (A~U) with aliases + extra non-category stocks
export const scanStocks: ScanStock[] = [
  ...categories.flatMap((c) =>
    c.stocks.map((s) => ({
      ticker: s.ticker,
      name: s.name,
      aliases: stockAliases[s.ticker],
    }))
  ),
  ...Object.entries(stockAliases)
    .filter(([ticker]) => !categories.some((c) => c.stocks.some((s) => s.ticker === ticker)))
    .map(([ticker, aliases]) => ({ ticker, name: stockLookup[ticker] ?? ticker, aliases })),
  { ticker: "7631", name: "聚賢研發-創", aliases: ["聚賢研發"] },
];

export function lookupStock(query: string): { ticker: string; stock_name: string } | null {
  const q = query.trim();
  if (!q) return null;
  const ql = q.toLowerCase();
  // 1. Check scan stocks by ticker, name, or alias
  for (const s of scanStocks) {
    if (s.ticker.toLowerCase() === ql) return { ticker: s.ticker, stock_name: s.name };
    if (s.name.toLowerCase() === ql) return { ticker: s.ticker, stock_name: s.name };
    if (s.aliases?.some((a) => a.toLowerCase() === ql)) return { ticker: s.ticker, stock_name: s.name };
  }
  // 2. Check broad lookup table by ticker
  const tickerMatch = Object.keys(stockLookup).find((t) => t.toLowerCase() === ql);
  if (tickerMatch) return { ticker: tickerMatch, stock_name: stockLookup[tickerMatch] };
  // 3. Check broad lookup table by name — also handles compound names like "三井金屬(Mitsui Kinzoku)"
  for (const [ticker, name] of Object.entries(stockLookup)) {
    if (name.toLowerCase() === ql) return { ticker, stock_name: name };
    const parts = name.split(/[\s()]+/).filter(Boolean);
    if (parts.some((p) => p.toLowerCase() === ql)) return { ticker, stock_name: name };
  }
  return null;
}
