// Comprehensive Taiwan stock ticker → name lookup map
// Covers: 0050 (台灣50), 0051 (中型100) constituents, popular ETFs, and other commonly traded stocks
// Used for auto-complete when adding stock tags

export const stockLookup: Record<string, { name: string; aliases?: string[] }> = {
  // ─── ETF ────────────────────────────────────────────────
  "0050": { name: "元大台灣50" },
  "0051": { name: "元大中型100" },
  "0052": { name: "富邦科技" },
  "0053": { name: "元大電子" },
  "0055": { name: "元大MSCI金融" },
  "0056": { name: "元大高股息" },
  "006205": { name: "富邦上証" },
  "006208": { name: "富邦台50" },
  "00690": { name: "兆豐藍籌30" },
  "00692": { name: "富邦公司治理" },
  "00701": { name: "國泰股利精選30" },
  "00713": { name: "元大台灣高息低波" },
  "00733": { name: "富邦臺灣中小" },
  "00850": { name: "元大臺灣ESG永續" },
  "00878": { name: "國泰永續高股息" },
  "00881": { name: "國泰台灣5G+" },
  "00882": { name: "中信中國高股息" },
  "00885": { name: "富邦越南" },
  "00891": { name: "中信關鍵半導體" },
  "00892": { name: "富邦台灣半導體" },
  "00893": { name: "國泰智能電動車" },
  "00894": { name: "中信小資高價30" },
  "00895": { name: "富邦未來車" },
  "00896": { name: "中信綠能及電動車" },
  "00900": { name: "富邦特選高股息30" },
  "00919": { name: "群益台灣精選高息" },
  "00929": { name: "復華台灣科技優息" },
  "00934": { name: "中信成長高股息" },
  "00935": { name: "野村台灣新科技50" },
  "00936": { name: "台新臺灣永續高息中小型" },
  "00939": { name: "統一台灣高息動能" },
  "00940": { name: "元大台灣價值高息" },
  "00941": { name: "中信上游半導體" },

  // ─── 0050 成分股（台灣50）────────────────────────────────
  "1101": { name: "台泥" },
  "1216": { name: "統一" },
  "1301": { name: "台塑" },
  "1303": { name: "南亞" },
  "1326": { name: "台化" },
  "2002": { name: "中鋼" },
  "2207": { name: "和泰車" },
  "2301": { name: "光寶科" },
  "2303": { name: "聯電" },
  "2308": { name: "台達電" },
  "2317": { name: "鴻海" },
  "2327": { name: "國巨" },
  "2330": { name: "台積電" },
  "2345": { name: "智邦" },
  "2357": { name: "華碩" },
  "2379": { name: "瑞昱" },
  "2382": { name: "廣達" },
  "2395": { name: "研華" },
  "2412": { name: "中華電" },
  "2454": { name: "聯發科" },
  "2474": { name: "可成" },
  "2603": { name: "長榮" },
  "2880": { name: "華南金" },
  "2881": { name: "富邦金" },
  "2882": { name: "國泰金" },
  "2883": { name: "開發金" },
  "2884": { name: "玉山金" },
  "2885": { name: "元大金" },
  "2886": { name: "兆豐金" },
  "2887": { name: "台新金" },
  "2890": { name: "永豐金" },
  "2891": { name: "中信金" },
  "2892": { name: "第一金" },
  "2912": { name: "統一超" },
  "3008": { name: "大立光" },
  "3034": { name: "聯詠" },
  "3037": { name: "欣興" },
  "3045": { name: "台灣大" },
  "3231": { name: "緯創" },
  "3661": { name: "世芯-KY" },
  "3711": { name: "日月光投控" },
  "4904": { name: "遠傳" },
  "4938": { name: "和碩" },
  "5876": { name: "上海商銀" },
  "5880": { name: "合庫金" },
  "6415": { name: "矽力-KY" },
  "6446": { name: "藥華藥" },
  "6505": { name: "台塑化" },
  "6669": { name: "緯穎" },

  // ─── 0051 成分股（中型100）及其他上市櫃常見個股 ──────────
  "1102": { name: "亞泥" },
  "1227": { name: "佳格" },
  "1229": { name: "聯華" },
  "1304": { name: "台聚" },
  "1314": { name: "中石化" },
  "1402": { name: "遠東新" },
  "1434": { name: "福懋" },
  "1440": { name: "南紡" },
  "1476": { name: "儒鴻" },
  "1477": { name: "聚陽" },
  "1504": { name: "東元" },
  "1560": { name: "中砂" },
  "1590": { name: "亞德客-KY" },
  "1597": { name: "直得", aliases: ["直得科技"] },
  "1605": { name: "華新" },
  "1722": { name: "台肥" },
  "1727": { name: "中華化" },
  "1802": { name: "台玻" },
  "1907": { name: "永豐餘" },
  "2006": { name: "東鋼" },
  "2014": { name: "中鴻" },
  "2015": { name: "豐興" },
  "2049": { name: "上銀" },
  "2059": { name: "川湖" },
  "2101": { name: "南港" },
  "2105": { name: "正新" },
  "2201": { name: "裕隆" },
  "2204": { name: "中華" },
  "2227": { name: "裕日車" },
  "2312": { name: "金寶" },
  "2313": { name: "華通" },
  "2324": { name: "仁寶" },
  "2337": { name: "旺宏" },
  "2344": { name: "華邦電" },
  "2347": { name: "聯強" },
  "2352": { name: "佳世達" },
  "2353": { name: "宏碁" },
  "2356": { name: "英業達" },
  "2360": { name: "致茂" },
  "2376": { name: "技嘉" },
  "2377": { name: "微星" },
  "2383": { name: "台光電" },
  "2385": { name: "群光" },
  "2388": { name: "威盛" },
  "2392": { name: "正崴" },
  "2404": { name: "漢唐" },
  "2408": { name: "南亞科" },
  "2449": { name: "京元電子" },
  "2451": { name: "創見" },
  "2455": { name: "全新" },
  "2458": { name: "義隆" },
  "2467": { name: "志聖" },
  "2472": { name: "立隆電", aliases: ["立隆電子"] },
  "2492": { name: "華新科" },
  "2498": { name: "宏達電" },
  "2542": { name: "興富發" },
  "2545": { name: "皇翔" },
  "2548": { name: "華固" },
  "2606": { name: "裕民" },
  "2609": { name: "陽明" },
  "2610": { name: "華航" },
  "2615": { name: "萬海" },
  "2618": { name: "長榮航" },
  "2633": { name: "台灣高鐵" },
  "2634": { name: "漢翔" },
  "2645": { name: "長榮航太" },
  "2801": { name: "彰銀" },
  "2809": { name: "京城銀" },
  "2812": { name: "台中銀" },
  "2834": { name: "臺企銀" },
  "2838": { name: "聯邦銀" },
  "2845": { name: "遠東銀" },
  "2855": { name: "統一證" },
  "2867": { name: "三商壽" },
  "2888": { name: "新光金" },
  "2889": { name: "國票金" },
  "2903": { name: "遠百" },
  "2904": { name: "匯僑-KY" },
  "2915": { name: "潤泰全" },
  "3003": { name: "健鼎" },
  "3004": { name: "豐達科" },
  "3006": { name: "晶豪科" },
  "3017": { name: "奇鋐" },
  "3023": { name: "信邦" },
  "3035": { name: "智原" },
  "3036": { name: "文曄" },
  "3044": { name: "健鼎" },
  "3049": { name: "和鑫" },
  "3058": { name: "立德" },
  "3081": { name: "聯亞" },
  "3105": { name: "穩懋" },
  "3131": { name: "弘塑" },
  "3189": { name: "景碩" },
  "3260": { name: "威剛" },
  "3296": { name: "勝德" },
  "3324": { name: "雙鴻" },
  "3357": { name: "臺慶科" },
  "3376": { name: "新日興" },
  "3443": { name: "創意" },
  "3450": { name: "聯鈞" },
  "3481": { name: "群創" },
  "3515": { name: "華擎" },
  "3529": { name: "力旺" },
  "3533": { name: "嘉澤" },
  "3563": { name: "牧德" },
  "3583": { name: "辛耘" },
  "3587": { name: "閎康" },
  "3588": { name: "通嘉" },
  "3596": { name: "智易" },
  "3615": { name: "安可" },
  "3617": { name: "碩天" },
  "3653": { name: "健策" },
  "3665": { name: "貿聯-KY" },
  "3680": { name: "家登" },
  "3686": { name: "達能" },
  "3690": { name: "美磊" },
  "3694": { name: "海華" },
  "3702": { name: "大聯大" },
  "3706": { name: "神達" },
  "3715": { name: "定穎投控" },
  "4142": { name: "國光生" },
  "4552": { name: "力達-KY" },
  "4576": { name: "大銀微系統", aliases: ["大銀微"] },
  "4743": { name: "合一" },
  "4746": { name: "台耀" },
  "4906": { name: "正文" },
  "4919": { name: "新唐" },
  "4927": { name: "泰鼎-KY" },
  "4958": { name: "臻鼎-KY" },
  "4961": { name: "天鈺" },
  "4966": { name: "譜瑞-KY" },
  "4967": { name: "十銓" },
  "5222": { name: "全訊" },
  "5234": { name: "達興材料" },
  "5269": { name: "祥碩" },
  "5274": { name: "信驊" },
  "5285": { name: "界霖" },
  "5306": { name: "桂盟" },
  "5347": { name: "世界" },
  "5388": { name: "中磊" },
  "5425": { name: "台半" },
  "5469": { name: "瀚宇博" },
  "5483": { name: "中美晶" },
  "5871": { name: "中租-KY" },
  "5903": { name: "全家" },
  "5904": { name: "寶雅" },
  "6005": { name: "群益證" },
  "6116": { name: "彩晶" },
  "6120": { name: "達運" },
  "6139": { name: "亞翔" },
  "6176": { name: "瑞儀" },
  "6191": { name: "精成科" },
  "6196": { name: "帆宣" },
  "6197": { name: "佳必琪" },
  "6213": { name: "聯茂" },
  "6223": { name: "旺矽" },
  "6230": { name: "超眾" },
  "6239": { name: "力成" },
  "6257": { name: "矽格" },
  "6269": { name: "台郡" },
  "6271": { name: "同欣電" },
  "6274": { name: "台燿" },
  "6278": { name: "台表科" },
  "6285": { name: "啟碁" },
  "6414": { name: "樺漢" },
  "6431": { name: "光麗-KY" },
  "6438": { name: "迅得" },
  "6449": { name: "鈺邦" },
  "6451": { name: "訊芯-KY" },
  "6456": { name: "GIS-KY" },
  "6488": { name: "環球晶" },
  "6504": { name: "南六" },
  "6510": { name: "精測" },
  "6515": { name: "穎崴" },
  "6523": { name: "達爾膚" },
  "6531": { name: "愛普" },
  "6533": { name: "晶心科" },
  "6547": { name: "高端疫苗" },
  "6552": { name: "易華電" },
  "6573": { name: "虹揚-KY" },
  "6581": { name: "鋼聯" },
  "6584": { name: "南俊國際" },
  "6592": { name: "和潤企業" },
  "6605": { name: "帝寶" },
  "6625": { name: "必應" },
  "6643": { name: "戎美-KY" },
  "6664": { name: "群翊" },
  "6666": { name: "羅麗芬-KY" },
  "6668": { name: "中揚光" },
  "6670": { name: "復盛應用" },
  "6672": { name: "騰輝電子-KY" },
  "6719": { name: "力智" },
  "6752": { name: "未秧-KY" },
  "6753": { name: "龍德造船" },
  "6756": { name: "威鋒電子" },
  "6768": { name: "志強-KY" },
  "6770": { name: "力積電" },
  "6781": { name: "AES-KY" },
  "6789": { name: "采鈺" },
  "6805": { name: "富世達" },
  "6826": { name: "和淞" },
  "6862": { name: "三集瑞-KY", aliases: ["三集瑞"] },
  "6890": { name: "來億-KY" },
  "6894": { name: "衛司特" },
  "6937": { name: "天虹" },
  "6944": { name: "兆聯實業", aliases: ["兆聯"] },
  "6953": { name: "家碩" },
  "7822": { name: "倍利科" },
  "7853": { name: "政美應用" },
  "8008": { name: "建興電" },
  "8016": { name: "矽創" },
  "8027": { name: "鈦昇" },
  "8033": { name: "雷虎", aliases: ["雷虎科技"] },
  "8042": { name: "金山電" },
  "8046": { name: "南電" },
  "8069": { name: "元太" },
  "8086": { name: "宏捷科" },
  "8112": { name: "至上" },
  "8150": { name: "南茂" },
  "8210": { name: "勤誠" },
  "8213": { name: "志超" },
  "8255": { name: "朋程" },
  "8261": { name: "富鼎" },
  "8271": { name: "宇瞻" },
  "8299": { name: "群聯" },
  "8341": { name: "日友" },
  "8358": { name: "金居" },
  "8454": { name: "富邦媒" },
  "8462": { name: "柏文" },
  "8464": { name: "億豐" },
  "8936": { name: "國統" },
  "9802": { name: "鈺齊-KY" },
  "9904": { name: "寶成" },
  "9910": { name: "豐泰" },
  "9914": { name: "美利達" },
  "9921": { name: "巨大" },
  "9927": { name: "泰銘" },
  "9933": { name: "中鼎" },
  "9938": { name: "百和" },
  "9939": { name: "宏全" },
  "9941": { name: "裕融" },
  "9945": { name: "潤泰新" },
  "4991": { name: "環宇-KY" },

  // ─── 美國 ETF ──────────────────────────────────────────
  "SPY": { name: "SPDR S&P 500 ETF" },
  "VOO": { name: "Vanguard S&P 500 ETF" },
  "IVV": { name: "iShares Core S&P 500 ETF" },
  "QQQ": { name: "Invesco QQQ (Nasdaq 100)" },
  "QQQM": { name: "Invesco Nasdaq 100 ETF" },
  "SOXX": { name: "iShares Semiconductor ETF" },
  "SMH": { name: "VanEck Semiconductor ETF" },
  "VTI": { name: "Vanguard Total Stock Market ETF" },
  "VGT": { name: "Vanguard IT ETF" },
  "XLK": { name: "Technology Select Sector SPDR" },
  "XLF": { name: "Financial Select Sector SPDR" },
  "XLE": { name: "Energy Select Sector SPDR" },
  "XLV": { name: "Health Care Select Sector SPDR" },
  "XLI": { name: "Industrial Select Sector SPDR" },
  "XLP": { name: "Consumer Staples Select Sector SPDR" },
  "XLY": { name: "Consumer Discretionary Select SPDR" },
  "ARKK": { name: "ARK Innovation ETF" },
  "DIA": { name: "SPDR Dow Jones Industrial ETF" },
  "IWM": { name: "iShares Russell 2000 ETF" },
  "VT": { name: "Vanguard Total World Stock ETF" },
  "VXUS": { name: "Vanguard Total Intl Stock ETF" },
  "EEM": { name: "iShares MSCI Emerging Markets ETF" },

  // ─── 美國 VOO/S&P 500 + QQQ/Nasdaq 100 + SOXX 成分股 ──
  // Top mega-cap
  "AAPL": { name: "Apple" },
  "MSFT": { name: "Microsoft" },
  "AMZN": { name: "Amazon" },
  "NVDA": { name: "NVIDIA" },
  "GOOGL": { name: "Alphabet A" },
  "GOOG": { name: "Alphabet C" },
  "META": { name: "Meta" },
  "BRK.B": { name: "Berkshire Hathaway" },
  "TSLA": { name: "Tesla" },
  "UNH": { name: "UnitedHealth" },
  "XOM": { name: "ExxonMobil" },
  "JNJ": { name: "Johnson & Johnson" },
  "JPM": { name: "JPMorgan Chase" },
  "V": { name: "Visa" },
  "PG": { name: "Procter & Gamble" },
  "MA": { name: "Mastercard" },
  "AVGO": { name: "Broadcom" },
  "HD": { name: "Home Depot" },
  "CVX": { name: "Chevron" },
  "MRK": { name: "Merck" },
  "LLY": { name: "Eli Lilly" },
  "ABBV": { name: "AbbVie" },
  "PEP": { name: "PepsiCo" },
  "KO": { name: "Coca-Cola" },
  "COST": { name: "Costco" },
  "BAC": { name: "Bank of America" },
  "ADBE": { name: "Adobe" },
  "WMT": { name: "Walmart" },
  "MCD": { name: "McDonald's" },
  "CRM": { name: "Salesforce" },
  "CSCO": { name: "Cisco" },
  "TMO": { name: "Thermo Fisher" },
  "ACN": { name: "Accenture" },
  "ABT": { name: "Abbott" },
  "NFLX": { name: "Netflix" },
  "DHR": { name: "Danaher" },
  "LIN": { name: "Linde" },
  "TXN": { name: "Texas Instruments" },
  "CMCSA": { name: "Comcast" },
  "NKE": { name: "Nike" },
  "PM": { name: "Philip Morris" },
  "ORCL": { name: "Oracle" },
  // Semiconductor / SOXX
  "AMD": { name: "AMD" },
  "INTC": { name: "Intel" },
  "MU": { name: "Micron" },
  "SNDK": { name: "SanDisk", aliases: ["Sandisk"] },
  "QCOM": { name: "Qualcomm" },
  "AMAT": { name: "Applied Materials" },
  "LRCX": { name: "Lam Research" },
  "KLAC": { name: "KLA" },
  "ASML": { name: "ASML" },
  "MRVL": { name: "Marvell" },
  "ON": { name: "ON Semiconductor" },
  "SNPS": { name: "Synopsys" },
  "CDNS": { name: "Cadence" },
  "ARM": { name: "Arm Holdings" },
  "TSM": { name: "TSMC (ADR)" },
  "NXPI": { name: "NXP Semiconductors" },
  "ADI": { name: "Analog Devices" },
  "MPWR": { name: "Monolithic Power Systems" },
  "SWKS": { name: "Skyworks Solutions" },
  "QRVO": { name: "Qorvo" },
  "MCHP": { name: "Microchip Technology" },
  "TER": { name: "Teradyne" },
  "ENTG": { name: "Entegris" },
  "MKSI": { name: "MKS Instruments" },
  "LSCC": { name: "Lattice Semiconductor" },
  "WOLF": { name: "Wolfspeed" },
  "ACLS": { name: "Axcelis Technologies" },
  "CRUS": { name: "Cirrus Logic" },
  "SLAB": { name: "Silicon Labs" },
  "DIOD": { name: "Diodes" },
  "MTSI": { name: "MACOM Technology" },
  "SITM": { name: "SiTime" },
  "RMBS": { name: "Rambus" },
  "COHR": { name: "Coherent" },
  "LITE": { name: "Lumentum" },
  "AMKR": { name: "Amkor Technology" },
  "FORM": { name: "FormFactor" },
  "ONTO": { name: "Onto Innovation" },
  "POWI": { name: "Power Integrations" },
  "ALGM": { name: "Allegro MicroSystems" },
  "GFS": { name: "GlobalFoundries" },
  "UMC": { name: "UMC (ADR)" },
  "ASX": { name: "ASE Technology (ADR)" },
  "STM": { name: "STMicroelectronics" },
  "IFX": { name: "Infineon" },
  // Tech / Software / Cloud (QQQ)
  "DELL": { name: "Dell" },
  "HPE": { name: "HP Enterprise" },
  "HPQ": { name: "HP Inc" },
  "SMCI": { name: "Super Micro Computer" },
  "PLTR": { name: "Palantir" },
  "SNOW": { name: "Snowflake" },
  "CRWD": { name: "CrowdStrike" },
  "PANW": { name: "Palo Alto Networks" },
  "ABNB": { name: "Airbnb" },
  "UBER": { name: "Uber" },
  "SQ": { name: "Block (Square)" },
  "SHOP": { name: "Shopify" },
  "COIN": { name: "Coinbase" },
  "SOFI": { name: "SoFi" },
  "NOW": { name: "ServiceNow" },
  "INTU": { name: "Intuit" },
  "WDAY": { name: "Workday" },
  "ZS": { name: "Zscaler" },
  "DDOG": { name: "Datadog" },
  "NET": { name: "Cloudflare" },
  "MDB": { name: "MongoDB" },
  "TEAM": { name: "Atlassian" },
  "VEEV": { name: "Veeva Systems" },
  "FTNT": { name: "Fortinet" },
  "ANSS": { name: "Ansys" },
  "TTD": { name: "The Trade Desk" },
  "DASH": { name: "DoorDash" },
  "MELI": { name: "MercadoLibre" },
  "SE": { name: "Sea Limited" },
  "BKNG": { name: "Booking Holdings" },
  "CPRT": { name: "Copart" },
  "MNST": { name: "Monster Beverage" },
  "ADP": { name: "ADP" },
  "PAYX": { name: "Paychex" },
  "CTAS": { name: "Cintas" },
  "ODFL": { name: "Old Dominion Freight" },
  "FAST": { name: "Fastenal" },
  "EA": { name: "Electronic Arts" },
  "TTWO": { name: "Take-Two Interactive" },
  "ATVI": { name: "Activision Blizzard" },
  "ROKU": { name: "Roku" },
  "ZM": { name: "Zoom Video" },
  "DOCU": { name: "DocuSign" },
  "OKTA": { name: "Okta" },
  "SPLK": { name: "Splunk" },
  "PINS": { name: "Pinterest" },
  "SNAP": { name: "Snap" },
  "LYFT": { name: "Lyft" },
  "RBLX": { name: "Roblox" },
  "U": { name: "Unity Software" },
  "PATH": { name: "UiPath" },
  "CFLT": { name: "Confluent" },
  "BILL": { name: "Bill Holdings" },
  "HUBS": { name: "HubSpot" },
  "TWLO": { name: "Twilio" },
  // EV / Automotive
  "RIVN": { name: "Rivian" },
  "LCID": { name: "Lucid" },
  "NIO": { name: "NIO" },
  "XPEV": { name: "XPeng" },
  "LI": { name: "Li Auto" },
  "GM": { name: "General Motors" },
  "F": { name: "Ford Motor" },
  "TM": { name: "Toyota Motor (ADR)" },
  "HMC": { name: "Honda Motor (ADR)" },
  // Aerospace & Defense
  "BA": { name: "Boeing" },
  "LMT": { name: "Lockheed Martin" },
  "RTX": { name: "RTX (Raytheon)" },
  "GE": { name: "GE Aerospace" },
  "NOC": { name: "Northrop Grumman" },
  "GD": { name: "General Dynamics" },
  "HII": { name: "Huntington Ingalls" },
  "LHX": { name: "L3Harris Technologies" },
  "TDG": { name: "TransDigm" },
  // Industrials
  "CAT": { name: "Caterpillar" },
  "DE": { name: "Deere & Company" },
  "HON": { name: "Honeywell" },
  "UNP": { name: "Union Pacific" },
  "UPS": { name: "UPS" },
  "FDX": { name: "FedEx" },
  "MMM": { name: "3M" },
  "EMR": { name: "Emerson Electric" },
  "ETN": { name: "Eaton" },
  "ITW": { name: "Illinois Tool Works" },
  "ROK": { name: "Rockwell Automation" },
  "PH": { name: "Parker-Hannifin" },
  "IR": { name: "Ingersoll Rand" },
  "AME": { name: "Ametek" },
  "GWW": { name: "W.W. Grainger" },
  "SHW": { name: "Sherwin-Williams" },
  "APD": { name: "Air Products" },
  "ECL": { name: "Ecolab" },
  "DD": { name: "DuPont" },
  "DOW": { name: "Dow Inc" },
  "PPG": { name: "PPG Industries" },
  "FCX": { name: "Freeport-McMoRan" },
  "NEM": { name: "Newmont" },
  // Entertainment / Media
  "DIS": { name: "Walt Disney" },
  "PARA": { name: "Paramount Global" },
  "WBD": { name: "Warner Bros Discovery" },
  "FOX": { name: "Fox Corp" },
  // Financials
  "PYPL": { name: "PayPal" },
  "GS": { name: "Goldman Sachs" },
  "MS": { name: "Morgan Stanley" },
  "C": { name: "Citigroup" },
  "WFC": { name: "Wells Fargo" },
  "SCHW": { name: "Charles Schwab" },
  "BLK": { name: "BlackRock" },
  "AXP": { name: "American Express" },
  "SPGI": { name: "S&P Global" },
  "ICE": { name: "Intercontinental Exchange" },
  "CME": { name: "CME Group" },
  "MCO": { name: "Moody's" },
  "MSCI": { name: "MSCI" },
  "AON": { name: "Aon" },
  "MMC": { name: "Marsh & McLennan" },
  "AIG": { name: "AIG" },
  "PRU": { name: "Prudential Financial" },
  "MET": { name: "MetLife" },
  "TRV": { name: "Travelers" },
  "CB": { name: "Chubb" },
  "AFL": { name: "Aflac" },
  "ALL": { name: "Allstate" },
  "PGR": { name: "Progressive" },
  "USB": { name: "U.S. Bancorp" },
  "PNC": { name: "PNC Financial" },
  "TFC": { name: "Truist Financial" },
  "COF": { name: "Capital One" },
  "FIS": { name: "Fidelity National Info" },
  "FISV": { name: "Fiserv" },
  // Healthcare / Biotech / Pharma
  "PFE": { name: "Pfizer" },
  "BMY": { name: "Bristol-Myers Squibb" },
  "AMGN": { name: "Amgen" },
  "GILD": { name: "Gilead Sciences" },
  "ISRG": { name: "Intuitive Surgical" },
  "MDT": { name: "Medtronic" },
  "SYK": { name: "Stryker" },
  "REGN": { name: "Regeneron" },
  "VRTX": { name: "Vertex Pharmaceuticals" },
  "BSX": { name: "Boston Scientific" },
  "ZBH": { name: "Zimmer Biomet" },
  "EW": { name: "Edwards Lifesciences" },
  "DXCM": { name: "DexCom" },
  "IDXX": { name: "Idexx Laboratories" },
  "IQV": { name: "IQVIA" },
  "A": { name: "Agilent Technologies" },
  "BDX": { name: "Becton Dickinson" },
  "BAX": { name: "Baxter International" },
  "BIIB": { name: "Biogen" },
  "MRNA": { name: "Moderna" },
  "ILMN": { name: "Illumina" },
  "HOLX": { name: "Hologic" },
  "ALGN": { name: "Align Technology" },
  "TECH": { name: "Bio-Techne" },
  // Consumer / Retail
  "SBUX": { name: "Starbucks" },
  "TGT": { name: "Target" },
  "LOW": { name: "Lowe's" },
  "TJX": { name: "TJX Companies" },
  "ROST": { name: "Ross Stores" },
  "DG": { name: "Dollar General" },
  "DLTR": { name: "Dollar Tree" },
  "ORLY": { name: "O'Reilly Automotive" },
  "AZO": { name: "AutoZone" },
  "CMG": { name: "Chipotle" },
  "YUM": { name: "Yum! Brands" },
  "DKNG": { name: "DraftKings" },
  "MAR": { name: "Marriott" },
  "HLT": { name: "Hilton" },
  "RCL": { name: "Royal Caribbean" },
  "LVS": { name: "Las Vegas Sands" },
  // Consumer Staples
  "CL": { name: "Colgate-Palmolive" },
  "KMB": { name: "Kimberly-Clark" },
  "GIS": { name: "General Mills" },
  "K": { name: "Kellanova" },
  "HSY": { name: "Hershey" },
  "MDLZ": { name: "Mondelez" },
  "KHC": { name: "Kraft Heinz" },
  "STZ": { name: "Constellation Brands" },
  "MO": { name: "Altria" },
  "EL": { name: "Estee Lauder" },
  // Telecom / Utilities
  "T": { name: "AT&T" },
  "VZ": { name: "Verizon" },
  "TMUS": { name: "T-Mobile US" },
  "CHTR": { name: "Charter Communications" },
  "NEE": { name: "NextEra Energy" },
  "DUK": { name: "Duke Energy" },
  "SO": { name: "Southern Company" },
  "D": { name: "Dominion Energy" },
  "AEP": { name: "American Electric Power" },
  "SRE": { name: "Sempra" },
  // Energy
  "COP": { name: "ConocoPhillips" },
  "EOG": { name: "EOG Resources" },
  "SLB": { name: "Schlumberger" },
  "MPC": { name: "Marathon Petroleum" },
  "PSX": { name: "Phillips 66" },
  "VLO": { name: "Valero Energy" },
  "OXY": { name: "Occidental Petroleum" },
  "KMI": { name: "Kinder Morgan" },
  "WMB": { name: "Williams Companies" },
  "HAL": { name: "Halliburton" },
  // Real Estate
  "AMT": { name: "American Tower" },
  "PLD": { name: "Prologis" },
  "CCI": { name: "Crown Castle" },
  "EQIX": { name: "Equinix" },
  "SPG": { name: "Simon Property Group" },
  "PSA": { name: "Public Storage" },
  "O": { name: "Realty Income" },
  "DLR": { name: "Digital Realty" },
  "WELL": { name: "Welltower" },
  "AVB": { name: "AvalonBay" },
  // Optical / Photonics
  "AAOI": { name: "Applied Optoelectronics" },

  // ─── 韓國 KOSPI 50 主要成分股 ─────────────────────────
  "005930.KS": { name: "Samsung Electronics", aliases: ["Samsung", "三星"] },
  "000660.KS": { name: "SK Hynix" },
  "005935.KS": { name: "Samsung Electronics Pref" },
  "005380.KS": { name: "Hyundai Motor" },
  "000270.KS": { name: "Kia" },
  "051910.KS": { name: "LG Chem" },
  "006400.KS": { name: "Samsung SDI" },
  "035420.KS": { name: "Naver" },
  "035720.KS": { name: "Kakao" },
  "068270.KS": { name: "Celltrion" },
  "105560.KS": { name: "KB Financial" },
  "055550.KS": { name: "Shinhan Financial" },
  "086790.KS": { name: "Hana Financial" },
  "316140.KS": { name: "Woori Financial" },
  "003670.KS": { name: "Posco Holdings" },
  "034730.KS": { name: "SK" },
  "017670.KS": { name: "SK Telecom" },
  "030200.KS": { name: "KT" },
  "032830.KS": { name: "Samsung Life" },
  "066570.KS": { name: "LG Electronics" },
  "003550.KS": { name: "LG" },
  "373220.KS": { name: "LG Energy Solution" },
  "012330.KS": { name: "Hyundai Mobis" },
  "009150.KS": { name: "Samsung Electro-Mechanics" },
  "028260.KS": { name: "Samsung C&T" },
  "034020.KS": { name: "Doosan Enerbility" },
  "010130.KS": { name: "Korea Zinc" },
  "010950.KS": { name: "S-Oil" },
  "096770.KS": { name: "SK Innovation" },
  "011200.KS": { name: "HMM" },
  "036570.KS": { name: "NCsoft" },
  "259960.KS": { name: "Krafton" },
  "018260.KS": { name: "Samsung SDS" },
  "352820.KS": { name: "Hybe" },
  "011170.KS": { name: "Lotte Chemical" },
  "047050.KS": { name: "Posco International" },
  "402340.KS": { name: "SK Square" },
  "003490.KS": { name: "Korean Air" },
  "000810.KS": { name: "Samsung Fire & Marine" },

  // ─── 日本 Nikkei 225 主要成分股 ────────────────────────
  "7203.T": { name: "Toyota Motor" },
  "6758.T": { name: "Sony Group" },
  "6861.T": { name: "Keyence" },
  "8306.T": { name: "MUFG" },
  "9432.T": { name: "NTT" },
  "9984.T": { name: "SoftBank Group" },
  "6501.T": { name: "Hitachi" },
  "8035.T": { name: "Tokyo Electron" },
  "4063.T": { name: "Shin-Etsu Chemical" },
  "6902.T": { name: "Denso" },
  "7741.T": { name: "HOYA" },
  "4519.T": { name: "Chugai Pharmaceutical" },
  "6098.T": { name: "Recruit Holdings" },
  "7267.T": { name: "Honda Motor" },
  "6954.T": { name: "Fanuc" },
  "4568.T": { name: "Daiichi Sankyo" },
  "6857.T": { name: "Advantest" },
  "9433.T": { name: "KDDI" },
  "8058.T": { name: "Mitsubishi Corp" },
  "8031.T": { name: "Mitsui & Co" },
  "9983.T": { name: "Fast Retailing" },
  "4502.T": { name: "Takeda Pharmaceutical" },
  "7974.T": { name: "Nintendo" },
  "6723.T": { name: "Renesas Electronics" },
  "6762.T": { name: "TDK" },
  "6981.T": { name: "Murata Manufacturing" },
  "4062.T": { name: "Ibiden" },
  "7751.T": { name: "Canon" },
  "6367.T": { name: "Daikin Industries" },
  "6971.T": { name: "Kyocera" },
  "3382.T": { name: "Seven & i Holdings" },
  "2914.T": { name: "Japan Tobacco" },
  "4661.T": { name: "Oriental Land" },
  "5108.T": { name: "Bridgestone" },
  "7269.T": { name: "Suzuki Motor" },
  "7270.T": { name: "Subaru" },
  "2802.T": { name: "Ajinomoto" },
  "4901.T": { name: "Fujifilm" },
  "6301.T": { name: "Komatsu" },
  "6594.T": { name: "Nidec" },
  "7832.T": { name: "Bandai Namco" },
  "9434.T": { name: "SoftBank Corp" },
  "4543.T": { name: "Terumo" },
  "9613.T": { name: "NTT Data" },
  "6503.T": { name: "Mitsubishi Electric" },
  "7011.T": { name: "Mitsubishi Heavy Industries" },
  "8001.T": { name: "Itochu" },
  "8002.T": { name: "Marubeni" },
  "6146.T": { name: "Disco" },
  "6920.T": { name: "Lasertec" },
  "6526.T": { name: "Socionext" },
  "4755.T": { name: "Rakuten Group" },
  "6752.T": { name: "Panasonic" },
  "2413.T": { name: "M3" },
  "4307.T": { name: "Nomura Research Institute" },
  "6273.T": { name: "SMC" },
  "7735.T": { name: "Screen Holdings" },
  "3407.T": { name: "Asahi Kasei" },
  "5201.T": { name: "AGC" },
  "7733.T": { name: "Olympus" },
  "8766.T": { name: "Tokio Marine" },
  "8411.T": { name: "Mizuho Financial" },
  "8316.T": { name: "SMFG" },
  "6481.T": { name: "THK" },
  "6976.T": { name: "Taiyo Yuden", aliases: ["太陽誘電"] },
  "285A.T": { name: "KIOXIA", aliases: ["鎧俠"] },
};
