// Comprehensive stock ticker / name lookup
// Used for auto-complete when adding stock tags; also exports scanStocks and lookupStock for article detection

// ─────────────────────────────────────────────────────────
// Scan / detection layer
// ─────────────────────────────────────────────────────────

export type ScanStock = {
  ticker: string;
  name: string;
  aliases?: string[];
  tickerOnly?: true;
};

// All stocks for article auto-detection and text highlighting.
// Adding a new detection stock = one entry here (ticker + name + optional aliases).
export const scanStocks: ScanStock[] = [
  // ─── A IC設計 ────────────────────────────────────────────
  { ticker: "2379", name: "瑞昱",      aliases: ["Realtek"] },
  { ticker: "2454", name: "聯發科",    aliases: ["MediaTek"] },
  { ticker: "5274", name: "信驊",      aliases: ["Aspeed"] },
  // ─── B 晶圓代工 ──────────────────────────────────────────
  { ticker: "2303", name: "聯電",      aliases: ["UMC"] },
  { ticker: "2330", name: "台積電",    aliases: ["TSMC", "台積"] },
  { ticker: "5347", name: "世界",      aliases: ["VIS", "世界先進"] },
  // ─── C 半導體封測 ────────────────────────────────────────
  { ticker: "3711", name: "日月光",    aliases: ["ASE", "日月光投控"] },
  { ticker: "6239", name: "力成",      aliases: ["PTI"] },
  { ticker: "6257", name: "矽格",      aliases: ["Sigurd"] },
  // ─── D 半導體檢測 ────────────────────────────────────────
  { ticker: "3587", name: "閎康" },
  // ─── E 半導體耗材 ────────────────────────────────────────
  { ticker: "1560", name: "中砂",      aliases: ["KINIK"] },
  { ticker: "1727", name: "中華化",    aliases: ["中華化學"] },
  { ticker: "3680", name: "家登",      aliases: ["Gudeng"] },
  { ticker: "6488", name: "環球晶",    aliases: ["GlobalWafers"] },
  // ─── F 半導體廠務 ────────────────────────────────────────
  { ticker: "2404", name: "漢唐" },
  { ticker: "6196", name: "帆宣" },
  { ticker: "6826", name: "和淞" },
  // ─── G 半導體設備 ────────────────────────────────────────
  { ticker: "2467", name: "志聖" },
  { ticker: "3131", name: "弘塑" },
  { ticker: "3455", name: "由田" },
  { ticker: "3583", name: "辛耘" },
  { ticker: "6438", name: "迅得" },
  { ticker: "6664", name: "群翊" },
  { ticker: "6937", name: "天虹" },
  { ticker: "6953", name: "家碩" },
  { ticker: "7822", name: "倍利科" },
  { ticker: "7853", name: "政美應用" },
  { ticker: "8027", name: "鈦昇" },
  // ─── H III-V族 ───────────────────────────────────────────
  { ticker: "2455", name: "全新" },
  { ticker: "3081", name: "聯亞" },
  { ticker: "3105", name: "穩懋" },
  { ticker: "4979", name: "華星光" },
  { ticker: "4991", name: "環宇-KY",   aliases: ["環宇"] },
  { ticker: "8086", name: "宏捷科" },
  // ─── I 記憶體 ────────────────────────────────────────────
  { ticker: "2337", name: "旺宏",      aliases: ["Macronix", "MXIC"] },
  { ticker: "2344", name: "華邦電",    aliases: ["Winbond"] },
  { ticker: "2408", name: "南亞科",    aliases: ["Nanya", "南亞科技"] },
  { ticker: "3260", name: "威剛",      aliases: ["ADATA"] },
  { ticker: "6531", name: "愛普",      aliases: ["Ap Memory", "ApMemory"] },
  { ticker: "8299", name: "群聯",      aliases: ["Phison"] },
  // ─── J 品牌/ODM ──────────────────────────────────────────
  { ticker: "2317", name: "鴻海",      aliases: ["Foxconn", "Hon Hai"] },
  { ticker: "2382", name: "廣達",      aliases: ["Quanta"] },
  // ─── K 電子零組件 ────────────────────────────────────────
  { ticker: "2059", name: "川湖" },
  { ticker: "2301", name: "光寶科",    aliases: ["Lite-On", "光寶"] },
  { ticker: "2308", name: "台達電",    aliases: ["Delta", "台達"] },
  { ticker: "3017", name: "奇鋐",      aliases: ["Asia Vital", "AVC"] },
  { ticker: "3324", name: "雙鴻" },
  { ticker: "3533", name: "嘉澤" },
  { ticker: "4931", name: "新盛力" },
  { ticker: "6584", name: "南俊國際" },
  { ticker: "6805", name: "富世達" },
  { ticker: "8210", name: "勤誠" },
  // ─── L 被動元件 ──────────────────────────────────────────
  { ticker: "2428", name: "興勤" },
  { ticker: "2472", name: "立隆電" },
  { ticker: "2478", name: "大毅" },
  { ticker: "2493", name: "揚博" },
  { ticker: "3026", name: "禾伸堂" },
  { ticker: "3624", name: "光頡" },
  { ticker: "3357", name: "臺慶科" },
  { ticker: "6284", name: "佳邦" },
  { ticker: "6449", name: "鈺邦" },
  { ticker: "6485", name: "點序" },
  { ticker: "8042", name: "金山電" },
  // ─── M PCB ───────────────────────────────────────────────
  { ticker: "2313", name: "華通",      aliases: ["Compeq"] },
  { ticker: "3037", name: "欣興",      aliases: ["Unimicron"] },
  { ticker: "3715", name: "定穎投控",  aliases: ["定穎"] },
  { ticker: "4958", name: "臻鼎-KY",   aliases: ["臻鼎", "ZDT"] },
  { ticker: "6191", name: "精成科",    aliases: ["GCE"] },
  // ─── N 車用零組件 ────────────────────────────────────────
  { ticker: "2351", name: "順德" },
  { ticker: "6271", name: "同欣電",    aliases: ["Tong Hsing"] },
  { ticker: "8255", name: "朋程",      aliases: ["PanJit"] },
  // ─── O 功率元件 ──────────────────────────────────────────
  { ticker: "5425", name: "台半",      aliases: ["TSC"] },
  // ─── P 航太軍工 ──────────────────────────────────────────
  { ticker: "2645", name: "長榮航太" },
  { ticker: "3004", name: "豐達科" },
  { ticker: "5222", name: "全訊" },
  { ticker: "6753", name: "龍德造船" },
  // ─── Q 銅箔基板 ──────────────────────────────────────────
  { ticker: "2383", name: "台光電",    aliases: ["EMC", "台光"] },
  { ticker: "6274", name: "台燿",      aliases: ["Taiflex"] },
  { ticker: "8358", name: "金居",      aliases: ["Co-Tech"] },
  // ─── R 機器系統 ──────────────────────────────────────────
  { ticker: "4906", name: "正文" },
  { ticker: "5388", name: "中磊" },
  { ticker: "6285", name: "啟碁" },
  // ─── S 自行車 ────────────────────────────────────────────
  { ticker: "9914", name: "美利達" },
  { ticker: "5306", name: "桂盟" },
  // ─── T 循環經濟 ──────────────────────────────────────────
  { ticker: "6894", name: "衛司特" },
  { ticker: "8936", name: "國統" },
  // ─── U 紡織製鞋 ──────────────────────────────────────────
  { ticker: "6768", name: "志強-KY" },
  { ticker: "6890", name: "來億-KY" },
  { ticker: "9938", name: "百和" },
  // ─── 雲端/CSP ───────────────────────────────────────────
  { ticker: "AMZN",       name: "Amazon",                 aliases: ["AWS"] },
  { ticker: "MSFT",       name: "Microsoft",              aliases: ["Azure"] },
  { ticker: "GOOG",       name: "Alphabet",               aliases: ["Google", "GCP"] },
  // ─── 美股 ────────────────────────────────────────────────
  { ticker: "STM",        name: "STMicroelectronics",     aliases: ["STMicro"] },
  { ticker: "SNDK",       name: "Sandisk",                aliases: ["SanDisk"] },
  { ticker: "STX",        name: "Seagate" },
  { ticker: "AXTI",       name: "AXT" },
  { ticker: "AMKR",       name: "Amkor Technology",       aliases: ["Amkor"] },
  { ticker: "WDC",        name: "Western Digital" },
  { ticker: "ORCL",       name: "Oracle" },
  { ticker: "ON",         name: "ON Semiconductor",        aliases: ["安森美", "onsemi", "On Semi"] },
  { ticker: "TXN",        name: "Texas Instruments",       aliases: ["TI"] },
  { ticker: "MPWR",       name: "Monolithic Power Systems", aliases: ["MPS"] },
  { ticker: "FN",         name: "Fabrinet" },
  { ticker: "APH",        name: "Amphenol" },
  // ─── 台股（非 /stock 頁面）──────────────────────────────
  // ─── 石化/化工 ──────────────────────────────────────────
  { ticker: "1101",       name: "台泥" },
  { ticker: "1310",       name: "台苯" },
  { ticker: "1312",       name: "國喬" },
  { ticker: "1708",       name: "東鹼" },
  { ticker: "1709",       name: "和益" },
  { ticker: "1712",       name: "興農" },
  { ticker: "1722",       name: "台肥" },
  { ticker: "1723",       name: "中碳",         aliases: ["中鋼碳素"] },
  { ticker: "6505",       name: "台塑化",        aliases: ["台塑石化"] },
  { ticker: "5301.T",    name: "東海碳素",      aliases: ["Tokai Carbon"] },
  { ticker: "7631",       name: "聚賢研發-創",             aliases: ["聚賢研發"] },
  { ticker: "2327",       name: "國巨" },
  { ticker: "2441",       name: "超豐" },
  { ticker: "2481",       name: "強茂" },
  { ticker: "3163",       name: "波若威" },
  { ticker: "3363",       name: "上詮" },
  { ticker: "6525",       name: "捷敏-KY",               aliases: ["捷敏"] },
  { ticker: "6715",       name: "嘉基" },
  { ticker: "6799",       name: "來頡",                   aliases: ["來頡科技"] },
  { ticker: "8261",       name: "富鼎" },
  { ticker: "5536",       name: "聖暉" },
  { ticker: "6691",       name: "洋基工程" },
  { ticker: "6862",       name: "三集瑞-KY",             aliases: ["三集瑞"] },
  { ticker: "6944",       name: "兆聯實業",              aliases: ["兆聯"] },
  { ticker: "3013",       name: "晟銘電" },
  { ticker: "3675",       name: "德微" },
  { ticker: "3693",       name: "營邦" },
  { ticker: "4971",       name: "IET-KY" },
  { ticker: "6138",       name: "茂達" },
  { ticker: "6411",       name: "晶焱" },
  { ticker: "6435",       name: "大中" },
  { ticker: "6770",       name: "力積電" },
  { ticker: "7712",       name: "博盛半導體" },
  // ─── 中國 A 股 ──────────────────────────────────────────
  { ticker: "000636.SZ",  name: "風華高科" },
  { ticker: "002138.SZ",  name: "順絡電子",                aliases: ["順絡"] },
  { ticker: "002463.SZ",  name: "滬電股份",                aliases: ["滬電"] },
  { ticker: "300394.SZ",  name: "天孚通信",               aliases: ["TFC"] },
  { ticker: "300476.SZ",  name: "勝宏科技",              aliases: ["勝宏"] },
  { ticker: "600460.SS",  name: "士蘭微" },
  { ticker: "603228.SS",  name: "景旺電子",               aliases: ["景旺"] },
  { ticker: "603986.SS",  name: "兆易創新" },
  { ticker: "688396.SS",  name: "華潤微" },
  // ─── 日股 ────────────────────────────────────────────────
  { ticker: "3407.T",     name: "旭化成(Asahi Kasei)",     aliases: ["旭化成", "Asahi Kasei", "Asahi"] },
  { ticker: "3110.T",     name: "日東紡(Nittobo)",          aliases: ["日東紡", "Nittobo"] },
  { ticker: "1899.T",     name: "福田(Fukuda)",             aliases: ["福田", "Fukuda"] },
  { ticker: "5706.T",     name: "三井金屬(Mitsui Kinzoku)", aliases: ["三井金屬", "Mitsui Kinzoku"] },
  { ticker: "5801.T",     name: "古河電工(Furukawa)",        aliases: ["古河電工", "Furukawa"] },
  { ticker: "4004.T",     name: "昭和電工(Resonac)",         aliases: ["昭和電工", "Resonac"] },
  { ticker: "4182.T",     name: "三菱瓦斯化學(MGC)",         aliases: ["三菱瓦斯化學", "MGC"] },
  { ticker: "285A.T",     name: "鎧俠(Kioxia)",             aliases: ["鎧俠", "Kioxia"] },
  { ticker: "6976.T",     name: "Taiyo Yuden",              aliases: ["太陽誘電"] },
  { ticker: "6997.T",     name: "Chemi-Con",                aliases: ["佳美工", "ChemiCon"] },
  // ─── 韓股 ────────────────────────────────────────────────
  { ticker: "000157.KS",  name: "斗山(Doosan)",             aliases: ["斗山", "Doosan"] },
  // ─── 沙烏地 ──────────────────────────────────────────────
  { ticker: "2010.SR",    name: "沙特基礎工業(SABIC)",       aliases: ["沙特基礎工業", "SABIC", "Sabic"] },

  // ─── 台灣 ETF ────────────────────────────────────────────
  { ticker: "0050",   name: "元大台灣50" },
  { ticker: "0051",   name: "元大中型100" },
  { ticker: "0052",   name: "富邦科技" },
  { ticker: "0053",   name: "元大電子" },
  { ticker: "0055",   name: "元大MSCI金融" },
  { ticker: "0056",   name: "元大高股息" },
  { ticker: "006205", name: "富邦上証" },
  { ticker: "006208", name: "富邦台50" },
  { ticker: "00690",  name: "兆豐藍籌30" },
  { ticker: "00692",  name: "富邦公司治理" },
  { ticker: "00701",  name: "國泰股利精選30" },
  { ticker: "00713",  name: "元大台灣高息低波" },
  { ticker: "00733",  name: "富邦臺灣中小" },
  { ticker: "00850",  name: "元大臺灣ESG永續" },
  { ticker: "00878",  name: "國泰永續高股息" },
  { ticker: "00881",  name: "國泰台灣5G+" },
  { ticker: "00882",  name: "中信中國高股息" },
  { ticker: "00885",  name: "富邦越南" },
  { ticker: "00891",  name: "中信關鍵半導體" },
  { ticker: "00892",  name: "富邦台灣半導體" },
  { ticker: "00893",  name: "國泰智能電動車" },
  { ticker: "00894",  name: "中信小資高價30" },
  { ticker: "00895",  name: "富邦未來車" },
  { ticker: "00896",  name: "中信綠能及電動車" },
  { ticker: "00900",  name: "富邦特選高股息30" },
  { ticker: "00919",  name: "群益台灣精選高息" },
  { ticker: "00929",  name: "復華台灣科技優息" },
  { ticker: "00934",  name: "中信成長高股息" },
  { ticker: "00935",  name: "野村台灣新科技50" },
  { ticker: "00936",  name: "台新臺灣永續高息中小型" },
  { ticker: "00939",  name: "統一台灣高息動能" },
  { ticker: "00940",  name: "元大台灣價值高息" },
  { ticker: "00941",  name: "中信上游半導體" },

  // ─── 台灣上市（0050 成分股）──────────────────────────────
  { ticker: "1216", name: "統一" },
  { ticker: "1301", name: "台塑" },
  { ticker: "1303", name: "南亞" },
  { ticker: "1326", name: "台化" },
  { ticker: "2002", name: "中鋼" },
  { ticker: "2207", name: "和泰車" },
  { ticker: "2345", name: "智邦" },
  { ticker: "2357", name: "華碩" },
  { ticker: "2395", name: "研華" },
  { ticker: "2412", name: "中華電" },
  { ticker: "2474", name: "可成" },
  { ticker: "2603", name: "長榮" },
  { ticker: "2880", name: "華南金" },
  { ticker: "2881", name: "富邦金" },
  { ticker: "2882", name: "國泰金" },
  { ticker: "2883", name: "開發金" },
  { ticker: "2884", name: "玉山金" },
  { ticker: "2885", name: "元大金" },
  { ticker: "2886", name: "兆豐金" },
  { ticker: "2887", name: "台新金" },
  { ticker: "2890", name: "永豐金" },
  { ticker: "2891", name: "中信金" },
  { ticker: "2892", name: "第一金" },
  { ticker: "2912", name: "統一超" },
  { ticker: "3008", name: "大立光" },
  { ticker: "3034", name: "聯詠" },
  { ticker: "3045", name: "台灣大" },
  { ticker: "3231", name: "緯創" },
  { ticker: "3661", name: "世芯-KY" },
  { ticker: "4904", name: "遠傳" },
  { ticker: "4938", name: "和碩" },
  { ticker: "5876", name: "上海商銀" },
  { ticker: "5880", name: "合庫金" },
  { ticker: "6415", name: "矽力-KY",  aliases: ["矽力杰"] },
  { ticker: "6446", name: "藥華藥" },
  { ticker: "6669", name: "緯穎" },

  // ─── 台灣上市（0051 成分股及其他常見個股）────────────────
  { ticker: "1102", name: "亞泥" },
  { ticker: "1227", name: "佳格" },
  { ticker: "1229", name: "聯華" },
  { ticker: "1304", name: "台聚" },
  { ticker: "1314", name: "中石化" },
  { ticker: "1402", name: "遠東新" },
  { ticker: "1434", name: "福懋" },
  { ticker: "1440", name: "南紡" },
  { ticker: "1476", name: "儒鴻" },
  { ticker: "1477", name: "聚陽" },
  { ticker: "1504", name: "東元" },
  { ticker: "1590", name: "亞德客-KY" },
  { ticker: "1605", name: "華新" },
  { ticker: "1802", name: "台玻" },
  { ticker: "1815", name: "富喬" },
  { ticker: "1907", name: "永豐餘" },
  { ticker: "2006", name: "東鋼" },
  { ticker: "2014", name: "中鴻" },
  { ticker: "2015", name: "豐興" },
  { ticker: "2049", name: "上銀" },
  { ticker: "2101", name: "南港" },
  { ticker: "2105", name: "正新" },
  { ticker: "2201", name: "裕隆" },
  { ticker: "2204", name: "中華" },
  { ticker: "2227", name: "裕日車" },
  { ticker: "2312", name: "金寶" },
  { ticker: "2324", name: "仁寶" },
  { ticker: "2342", name: "茂矽" },
  { ticker: "2347", name: "聯強" },
  { ticker: "2352", name: "佳世達" },
  { ticker: "2353", name: "宏碁" },
  { ticker: "2356", name: "英業達" },
  { ticker: "2360", name: "致茂" },
  { ticker: "2376", name: "技嘉" },
  { ticker: "2377", name: "微星" },
  { ticker: "2385", name: "群光" },
  { ticker: "2388", name: "威盛" },
  { ticker: "2392", name: "正崴" },
  { ticker: "2449", name: "京元電子" },
  { ticker: "2451", name: "創見" },
  { ticker: "2458", name: "義隆" },
  { ticker: "2492", name: "華新科" },
  { ticker: "2498", name: "宏達電" },
  { ticker: "2542", name: "興富發" },
  { ticker: "2545", name: "皇翔" },
  { ticker: "2548", name: "華固" },
  { ticker: "2606", name: "裕民" },
  { ticker: "2609", name: "陽明" },
  { ticker: "2610", name: "華航" },
  { ticker: "2615", name: "萬海" },
  { ticker: "2618", name: "長榮航" },
  { ticker: "2633", name: "台灣高鐵" },
  { ticker: "2634", name: "漢翔" },
  { ticker: "2801", name: "彰銀" },
  { ticker: "2809", name: "京城銀" },
  { ticker: "2812", name: "台中銀" },
  { ticker: "2834", name: "臺企銀" },
  { ticker: "2838", name: "聯邦銀" },
  { ticker: "2845", name: "遠東銀" },
  { ticker: "2855", name: "統一證" },
  { ticker: "2867", name: "三商壽" },
  { ticker: "2888", name: "新光金" },
  { ticker: "2889", name: "國票金" },
  { ticker: "2903", name: "遠百" },
  { ticker: "2904", name: "匯僑-KY" },
  { ticker: "2915", name: "潤泰全" },
  { ticker: "3003", name: "健鼎" },
  { ticker: "3006", name: "晶豪科" },
  { ticker: "3023", name: "信邦" },
  { ticker: "3035", name: "智原" },
  { ticker: "3036", name: "文曄" },
  { ticker: "3044", name: "健鼎" },
  { ticker: "3049", name: "和鑫" },
  { ticker: "3058", name: "立德" },
  { ticker: "3189", name: "景碩" },
  { ticker: "3296", name: "勝德" },
  { ticker: "3376", name: "新日興" },
  { ticker: "3402", name: "漢科" },
  { ticker: "3443", name: "創意" },
  { ticker: "3450", name: "聯鈞" },
  { ticker: "3481", name: "群創" },
  { ticker: "3515", name: "華擎" },
  { ticker: "3529", name: "力旺" },
  { ticker: "3563", name: "牧德" },
  { ticker: "3588", name: "通嘉" },
  { ticker: "3596", name: "智易" },
  { ticker: "3611", name: "鼎翰" },
  { ticker: "3615", name: "安可" },
  { ticker: "3617", name: "碩天" },
  { ticker: "3653", name: "健策" },
  { ticker: "3665", name: "貿聯-KY" },
  { ticker: "3686", name: "達能" },
  { ticker: "3690", name: "美磊" },
  { ticker: "3694", name: "海華" },
  { ticker: "3702", name: "大聯大" },
  { ticker: "3706", name: "神達" },
  { ticker: "4142", name: "國光生" },
  { ticker: "4552", name: "力達-KY" },
  { ticker: "4722", name: "國精化" },
  { ticker: "4743", name: "合一" },
  { ticker: "4746", name: "台耀" },
  { ticker: "4764", name: "雙鍵" },
  { ticker: "4919", name: "新唐" },
  { ticker: "4927", name: "泰鼎-KY" },
  { ticker: "4961", name: "天鈺" },
  { ticker: "4966", name: "譜瑞-KY" },
  { ticker: "4967", name: "十銓" },
  { ticker: "5234", name: "達興材料" },
  { ticker: "5269", name: "祥碩" },
  { ticker: "5285", name: "界霖" },
  { ticker: "5340", name: "建榮" },
  { ticker: "5469", name: "瀚宇博" },
  { ticker: "5475", name: "德宏" },
  { ticker: "5483", name: "中美晶" },
  { ticker: "5871", name: "中租-KY" },
  { ticker: "5903", name: "全家" },
  { ticker: "5904", name: "寶雅" },
  { ticker: "6005", name: "群益證" },
  { ticker: "6116", name: "彩晶" },
  { ticker: "6120", name: "達運" },
  { ticker: "6139", name: "亞翔" },
  { ticker: "6147", name: "頎邦" },
  { ticker: "6175", name: "立敦" },
  { ticker: "6176", name: "瑞儀" },
  { ticker: "6187", name: "萬潤" },
  { ticker: "6197", name: "佳必琪" },
  { ticker: "6213", name: "聯茂" },
  { ticker: "6223", name: "旺矽" },
  { ticker: "6230", name: "超眾" },
  { ticker: "6269", name: "台郡" },
  { ticker: "6278", name: "台表科" },
  { ticker: "6414", name: "樺漢" },
  { ticker: "6431", name: "光麗-KY" },
  { ticker: "6451", name: "訊芯-KY" },
  { ticker: "6456", name: "GIS-KY" },
  { ticker: "6504", name: "南六" },
  { ticker: "6510", name: "精測" },
  { ticker: "6515", name: "穎崴" },
  { ticker: "6523", name: "達爾膚" },
  { ticker: "6533", name: "晶心科" },
  { ticker: "6547", name: "高端疫苗" },
  { ticker: "6552", name: "易華電" },
  { ticker: "6573", name: "虹揚-KY" },
  { ticker: "6581", name: "鋼聯" },
  { ticker: "6592", name: "和潤企業" },
  { ticker: "6605", name: "帝寶" },
  { ticker: "6625", name: "必應" },
  { ticker: "6640", name: "均華" },
  { ticker: "6643", name: "戎美-KY" },
  { ticker: "6666", name: "羅麗芬-KY" },
  { ticker: "6668", name: "中揚光" },
  { ticker: "6670", name: "復盛應用" },
  { ticker: "6672", name: "騰輝電子-KY" },
  { ticker: "6719", name: "力智" },
  { ticker: "6752", name: "未秧-KY" },
  { ticker: "6756", name: "威鋒電子" },
  { ticker: "6781", name: "AES-KY" },
  { ticker: "6789", name: "采鈺" },
  { ticker: "7703", name: "銳澤" },
  { ticker: "8008", name: "建興電" },
  { ticker: "8016", name: "矽創" },
  { ticker: "8046", name: "南電" },
  { ticker: "8069", name: "元太" },
  { ticker: "8112", name: "至上" },
  { ticker: "8150", name: "南茂" },
  { ticker: "8213", name: "志超" },
  { ticker: "8271", name: "宇瞻" },
  { ticker: "8341", name: "日友" },
  { ticker: "8454", name: "富邦媒" },
  { ticker: "8462", name: "柏文" },
  { ticker: "8464", name: "億豐" },
  { ticker: "9802", name: "鈺齊-KY" },
  { ticker: "9904", name: "寶成" },
  { ticker: "9910", name: "豐泰" },
  { ticker: "9921", name: "巨大" },
  { ticker: "9927", name: "泰銘" },
  { ticker: "9933", name: "中鼎" },
  { ticker: "9939", name: "宏全" },
  { ticker: "9941", name: "裕融" },
  { ticker: "9945", name: "潤泰新" },

  // ─── 美國 ETF ──────────────────────────────────────────
  { ticker: "SPY",  name: "SPDR S&P 500 ETF" },
  { ticker: "VOO",  name: "Vanguard S&P 500 ETF" },
  { ticker: "IVV",  name: "iShares Core S&P 500 ETF" },
  { ticker: "QQQ",  name: "Invesco QQQ (Nasdaq 100)" },
  { ticker: "QQQM", name: "Invesco Nasdaq 100 ETF" },
  { ticker: "SOXX", name: "iShares Semiconductor ETF" },
  { ticker: "SMH",  name: "VanEck Semiconductor ETF" },
  { ticker: "VTI",  name: "Vanguard Total Stock Market ETF" },
  { ticker: "VGT",  name: "Vanguard IT ETF" },
  { ticker: "XLK",  name: "Technology Select Sector SPDR" },
  { ticker: "XLF",  name: "Financial Select Sector SPDR" },
  { ticker: "XLE",  name: "Energy Select Sector SPDR" },
  { ticker: "XLV",  name: "Health Care Select Sector SPDR" },
  { ticker: "XLI",  name: "Industrial Select Sector SPDR" },
  { ticker: "XLP",  name: "Consumer Staples Select Sector SPDR" },
  { ticker: "XLY",  name: "Consumer Discretionary Select SPDR" },
  { ticker: "ARKK", name: "ARK Innovation ETF" },
  { ticker: "DIA",  name: "SPDR Dow Jones Industrial ETF" },
  { ticker: "IWM",  name: "iShares Russell 2000 ETF" },
  { ticker: "VT",   name: "Vanguard Total World Stock ETF" },
  { ticker: "VXUS", name: "Vanguard Total Intl Stock ETF" },
  { ticker: "EEM",  name: "iShares MSCI Emerging Markets ETF" },

  // ─── 美股（大型股）──────────────────────────────────────
  { ticker: "AAPL",  name: "Apple" },
  { ticker: "NVDA",  name: "NVIDIA" },
  { ticker: "META",  name: "Meta" },
  { ticker: "BRK.B", name: "Berkshire Hathaway" },
  { ticker: "TSLA",  name: "Tesla" },
  { ticker: "UNH",   name: "UnitedHealth" },
  { ticker: "XOM",   name: "ExxonMobil" },
  { ticker: "JNJ",   name: "Johnson & Johnson" },
  { ticker: "JPM",   name: "JPMorgan Chase" },
  { ticker: "V",     name: "Visa" },
  { ticker: "PG",    name: "Procter & Gamble" },
  { ticker: "MA",    name: "Mastercard" },
  { ticker: "AVGO",  name: "Broadcom" },
  { ticker: "HD",    name: "Home Depot" },
  { ticker: "CVX",   name: "Chevron" },
  { ticker: "MRK",   name: "Merck" },
  { ticker: "LLY",   name: "Eli Lilly" },
  { ticker: "ABBV",  name: "AbbVie" },
  { ticker: "PEP",   name: "PepsiCo" },
  { ticker: "KO",    name: "Coca-Cola" },
  { ticker: "COST",  name: "Costco" },
  { ticker: "BAC",   name: "Bank of America" },
  { ticker: "ADBE",  name: "Adobe" },
  { ticker: "WMT",   name: "Walmart" },
  { ticker: "MCD",   name: "McDonald's" },
  { ticker: "CRDO",  name: "Credo" },
  { ticker: "CRM",   name: "Salesforce" },
  { ticker: "CSCO",  name: "Cisco" },
  { ticker: "TMO",   name: "Thermo Fisher" },
  { ticker: "ACN",   name: "Accenture" },
  { ticker: "ABT",   name: "Abbott" },
  { ticker: "NFLX",  name: "Netflix" },
  { ticker: "DHR",   name: "Danaher" },
  { ticker: "LIN",   name: "Linde" },
  { ticker: "CMCSA", name: "Comcast" },
  { ticker: "NKE",   name: "Nike" },
  { ticker: "PM",    name: "Philip Morris" },
  // ─── 美股（半導體）─────────────────────────────────────
  { ticker: "AMD",   name: "AMD" },
  { ticker: "INTC",  name: "Intel" },
  { ticker: "MU",    name: "Micron" },
  { ticker: "QCOM",  name: "Qualcomm" },
  { ticker: "AMAT",  name: "Applied Materials" },
  { ticker: "LRCX",  name: "Lam Research" },
  { ticker: "KLAC",  name: "KLA" },
  { ticker: "ASML",  name: "ASML" },
  { ticker: "MRVL",  name: "Marvell" },
  { ticker: "SNPS",  name: "Synopsys" },
  { ticker: "CDNS",  name: "Cadence" },
  { ticker: "ARM",   name: "Arm Holdings" },
  { ticker: "TSM",   name: "TSMC (ADR)" },
  { ticker: "NXPI",  name: "NXP Semiconductors" },
  { ticker: "ADI",   name: "Analog Devices" },
  { ticker: "SWKS",  name: "Skyworks Solutions" },
  { ticker: "QRVO",  name: "Qorvo" },
  { ticker: "MCHP",  name: "Microchip Technology" },
  { ticker: "TER",   name: "Teradyne" },
  { ticker: "ENTG",  name: "Entegris" },
  { ticker: "MKSI",  name: "MKS Instruments" },
  { ticker: "LSCC",  name: "Lattice Semiconductor", aliases: ["Lattice"] },
  { ticker: "WOLF",  name: "Wolfspeed" },
  { ticker: "ACLS",  name: "Axcelis Technologies" },
  { ticker: "CRUS",  name: "Cirrus Logic" },
  { ticker: "SLAB",  name: "Silicon Labs" },
  { ticker: "DIOD",  name: "Diodes" },
  { ticker: "VSH",   name: "Vishay" },
  { ticker: "MTSI",  name: "MACOM Technology" },
  { ticker: "SITM",  name: "SiTime" },
  { ticker: "RMBS",  name: "Rambus" },
  { ticker: "COHR",  name: "Coherent" },
  { ticker: "LITE",  name: "Lumentum" },
  { ticker: "FORM",  name: "FormFactor" },
  { ticker: "ONTO",  name: "Onto Innovation" },
  { ticker: "POWI",  name: "Power Integrations" },
  { ticker: "ALGM",  name: "Allegro MicroSystems" },
  { ticker: "GFS",   name: "GlobalFoundries" },
  { ticker: "UMC",   name: "UMC (ADR)" },
  { ticker: "ASX",   name: "ASE Technology (ADR)" },
  { ticker: "IFX",   name: "Infineon" },
  { ticker: "AAOI",  name: "Applied Optoelectronics" },
  // ─── 美股（科技/雲端/軟體）────────────────────────────
  { ticker: "DELL",  name: "Dell" },
  { ticker: "HPE",   name: "HP Enterprise" },
  { ticker: "HPQ",   name: "HP Inc" },
  { ticker: "SMCI",  name: "Super Micro Computer" },
  { ticker: "PLTR",  name: "Palantir" },
  { ticker: "SNOW",  name: "Snowflake" },
  { ticker: "CRWD",  name: "CrowdStrike" },
  { ticker: "PANW",  name: "Palo Alto Networks" },
  { ticker: "ABNB",  name: "Airbnb" },
  { ticker: "UBER",  name: "Uber" },
  { ticker: "SQ",    name: "Block (Square)" },
  { ticker: "SHOP",  name: "Shopify" },
  { ticker: "COIN",  name: "Coinbase" },
  { ticker: "SOFI",  name: "SoFi" },
  { ticker: "NOW",   name: "ServiceNow" },
  { ticker: "INTU",  name: "Intuit" },
  { ticker: "WDAY",  name: "Workday" },
  { ticker: "ZS",    name: "Zscaler" },
  { ticker: "DDOG",  name: "Datadog" },
  { ticker: "NET",   name: "Cloudflare" },
  { ticker: "MDB",   name: "MongoDB" },
  { ticker: "TEAM",  name: "Atlassian" },
  { ticker: "VEEV",  name: "Veeva Systems" },
  { ticker: "FTNT",  name: "Fortinet" },
  { ticker: "ANSS",  name: "Ansys" },
  { ticker: "TTD",   name: "The Trade Desk" },
  { ticker: "DASH",  name: "DoorDash" },
  { ticker: "MELI",  name: "MercadoLibre" },
  { ticker: "SE",    name: "Sea Limited" },
  { ticker: "BKNG",  name: "Booking Holdings" },
  { ticker: "CPRT",  name: "Copart" },
  { ticker: "MNST",  name: "Monster Beverage" },
  { ticker: "ADP",   name: "ADP" },
  { ticker: "PAYX",  name: "Paychex" },
  { ticker: "CTAS",  name: "Cintas" },
  { ticker: "ODFL",  name: "Old Dominion Freight" },
  { ticker: "FAST",  name: "Fastenal" },
  { ticker: "EA",    name: "Electronic Arts" },
  { ticker: "TTWO",  name: "Take-Two Interactive" },
  { ticker: "ATVI",  name: "Activision Blizzard" },
  { ticker: "ROKU",  name: "Roku" },
  { ticker: "ZM",    name: "Zoom Video" },
  { ticker: "DOCU",  name: "DocuSign" },
  { ticker: "OKTA",  name: "Okta" },
  { ticker: "SPLK",  name: "Splunk" },
  { ticker: "PINS",  name: "Pinterest" },
  { ticker: "SNAP",  name: "Snap" },
  { ticker: "LYFT",  name: "Lyft" },
  { ticker: "RBLX",  name: "Roblox" },
  { ticker: "U",     name: "Unity Software" },
  { ticker: "PATH",  name: "UiPath" },
  { ticker: "CFLT",  name: "Confluent" },
  { ticker: "BILL",  name: "Bill Holdings" },
  { ticker: "HUBS",  name: "HubSpot" },
  { ticker: "TWLO",  name: "Twilio" },
  // ─── 美股（EV/汽車）────────────────────────────────────
  { ticker: "RIVN",  name: "Rivian" },
  { ticker: "LCID",  name: "Lucid" },
  { ticker: "NIO",   name: "NIO" },
  { ticker: "XPEV",  name: "XPeng" },
  { ticker: "LI",    name: "Li Auto" },
  { ticker: "GM",    name: "General Motors" },
  { ticker: "F",     name: "Ford Motor" },
  { ticker: "TM",    name: "Toyota Motor (ADR)" },
  { ticker: "HMC",   name: "Honda Motor (ADR)" },
  // ─── 美股（航太/國防）──────────────────────────────────
  { ticker: "BA",    name: "Boeing" },
  { ticker: "LMT",   name: "Lockheed Martin" },
  { ticker: "RTX",   name: "RTX (Raytheon)" },
  { ticker: "GE",    name: "GE Aerospace" },
  { ticker: "NOC",   name: "Northrop Grumman" },
  { ticker: "GD",    name: "General Dynamics" },
  { ticker: "HII",   name: "Huntington Ingalls" },
  { ticker: "LHX",   name: "L3Harris Technologies" },
  { ticker: "TDG",   name: "TransDigm" },
  // ─── 美股（工業）───────────────────────────────────────
  { ticker: "CAT",   name: "Caterpillar" },
  { ticker: "DE",    name: "Deere & Company" },
  { ticker: "HON",   name: "Honeywell" },
  { ticker: "UNP",   name: "Union Pacific" },
  { ticker: "UPS",   name: "UPS" },
  { ticker: "FDX",   name: "FedEx" },
  { ticker: "MMM",   name: "3M" },
  { ticker: "EMR",   name: "Emerson Electric" },
  { ticker: "ETN",   name: "Eaton" },
  { ticker: "ITW",   name: "Illinois Tool Works" },
  { ticker: "ROK",   name: "Rockwell Automation" },
  { ticker: "PH",    name: "Parker-Hannifin" },
  { ticker: "IR",    name: "Ingersoll Rand" },
  { ticker: "AME",   name: "Ametek" },
  { ticker: "GWW",   name: "W.W. Grainger" },
  { ticker: "SHW",   name: "Sherwin-Williams" },
  { ticker: "APD",   name: "Air Products" },
  { ticker: "ECL",   name: "Ecolab" },
  { ticker: "DD",    name: "DuPont" },
  { ticker: "DOW",   name: "Dow Inc" },
  { ticker: "PPG",   name: "PPG Industries" },
  { ticker: "FCX",   name: "Freeport-McMoRan" },
  { ticker: "NEM",   name: "Newmont" },
  // ─── 美股（娛樂/媒體）──────────────────────────────────
  { ticker: "DIS",   name: "Walt Disney" },
  { ticker: "PARA",  name: "Paramount Global" },
  { ticker: "WBD",   name: "Warner Bros Discovery" },
  { ticker: "FOX",   name: "Fox Corp" },
  // ─── 美股（金融）───────────────────────────────────────
  { ticker: "PYPL",  name: "PayPal" },
  { ticker: "GS",    name: "Goldman Sachs" },
  { ticker: "MS",    name: "Morgan Stanley" },
  { ticker: "C",     name: "Citigroup" },
  { ticker: "WFC",   name: "Wells Fargo" },
  { ticker: "SCHW",  name: "Charles Schwab" },
  { ticker: "BLK",   name: "BlackRock" },
  { ticker: "AXP",   name: "American Express" },
  { ticker: "SPGI",  name: "S&P Global" },
  { ticker: "ICE",   name: "Intercontinental Exchange" },
  { ticker: "CME",   name: "CME Group" },
  { ticker: "MCO",   name: "Moody's" },
  { ticker: "MSCI",  name: "MSCI" },
  { ticker: "AON",   name: "Aon" },
  { ticker: "MMC",   name: "Marsh & McLennan" },
  { ticker: "AIG",   name: "AIG" },
  { ticker: "PRU",   name: "Prudential Financial" },
  { ticker: "MET",   name: "MetLife" },
  { ticker: "TRV",   name: "Travelers" },
  { ticker: "CB",    name: "Chubb" },
  { ticker: "AFL",   name: "Aflac" },
  { ticker: "ALL",   name: "Allstate" },
  { ticker: "PGR",   name: "Progressive" },
  { ticker: "USB",   name: "U.S. Bancorp" },
  { ticker: "PNC",   name: "PNC Financial" },
  { ticker: "TFC",   name: "Truist Financial" },
  { ticker: "COF",   name: "Capital One" },
  { ticker: "FIS",   name: "Fidelity National Info" },
  { ticker: "FISV",  name: "Fiserv" },
  // ─── 美股（醫療/生技/製藥）────────────────────────────
  { ticker: "PFE",   name: "Pfizer" },
  { ticker: "BMY",   name: "Bristol-Myers Squibb" },
  { ticker: "AMGN",  name: "Amgen" },
  { ticker: "GILD",  name: "Gilead Sciences" },
  { ticker: "ISRG",  name: "Intuitive Surgical" },
  { ticker: "MDT",   name: "Medtronic" },
  { ticker: "SYK",   name: "Stryker" },
  { ticker: "REGN",  name: "Regeneron" },
  { ticker: "VRTX",  name: "Vertex Pharmaceuticals" },
  { ticker: "BSX",   name: "Boston Scientific" },
  { ticker: "ZBH",   name: "Zimmer Biomet" },
  { ticker: "EW",    name: "Edwards Lifesciences" },
  { ticker: "DXCM",  name: "DexCom" },
  { ticker: "IDXX",  name: "Idexx Laboratories" },
  { ticker: "IQV",   name: "IQVIA" },
  { ticker: "A",     name: "Agilent Technologies" },
  { ticker: "BDX",   name: "Becton Dickinson" },
  { ticker: "BAX",   name: "Baxter International" },
  { ticker: "BIIB",  name: "Biogen" },
  { ticker: "MRNA",  name: "Moderna" },
  { ticker: "ILMN",  name: "Illumina" },
  { ticker: "HOLX",  name: "Hologic" },
  { ticker: "ALGN",  name: "Align Technology" },
  { ticker: "TECH",  name: "Bio-Techne" },
  // ─── 美股（消費/零售）──────────────────────────────────
  { ticker: "SBUX",  name: "Starbucks" },
  { ticker: "TGT",   name: "Target" },
  { ticker: "LOW",   name: "Lowe's" },
  { ticker: "TJX",   name: "TJX Companies" },
  { ticker: "ROST",  name: "Ross Stores" },
  { ticker: "DG",    name: "Dollar General" },
  { ticker: "DLTR",  name: "Dollar Tree" },
  { ticker: "ORLY",  name: "O'Reilly Automotive" },
  { ticker: "AZO",   name: "AutoZone" },
  { ticker: "CMG",   name: "Chipotle" },
  { ticker: "YUM",   name: "Yum! Brands" },
  { ticker: "DKNG",  name: "DraftKings" },
  { ticker: "MAR",   name: "Marriott" },
  { ticker: "HLT",   name: "Hilton" },
  { ticker: "RCL",   name: "Royal Caribbean" },
  { ticker: "LVS",   name: "Las Vegas Sands" },
  // ─── 美股（消費必需品）─────────────────────────────────
  { ticker: "CL",    name: "Colgate-Palmolive" },
  { ticker: "KMB",   name: "Kimberly-Clark" },
  { ticker: "GIS",   name: "General Mills" },
  { ticker: "K",     name: "Kellanova" },
  { ticker: "HSY",   name: "Hershey" },
  { ticker: "MDLZ",  name: "Mondelez" },
  { ticker: "KHC",   name: "Kraft Heinz" },
  { ticker: "STZ",   name: "Constellation Brands" },
  { ticker: "MO",    name: "Altria" },
  { ticker: "EL",    name: "Estee Lauder" },
  // ─── 美股（電信/公用事業）──────────────────────────────
  { ticker: "T",     name: "AT&T" },
  { ticker: "VZ",    name: "Verizon" },
  { ticker: "TMUS",  name: "T-Mobile US" },
  { ticker: "CHTR",  name: "Charter Communications" },
  { ticker: "NEE",   name: "NextEra Energy" },
  { ticker: "DUK",   name: "Duke Energy" },
  { ticker: "SO",    name: "Southern Company" },
  { ticker: "D",     name: "Dominion Energy" },
  { ticker: "AEP",   name: "American Electric Power" },
  { ticker: "SRE",   name: "Sempra" },
  // ─── 美股（能源）───────────────────────────────────────
  { ticker: "COP",   name: "ConocoPhillips" },
  { ticker: "EOG",   name: "EOG Resources" },
  { ticker: "SLB",   name: "Schlumberger" },
  { ticker: "MPC",   name: "Marathon Petroleum" },
  { ticker: "PSX",   name: "Phillips 66" },
  { ticker: "VLO",   name: "Valero Energy" },
  { ticker: "OXY",   name: "Occidental Petroleum" },
  { ticker: "KMI",   name: "Kinder Morgan" },
  { ticker: "WMB",   name: "Williams Companies" },
  { ticker: "HAL",   name: "Halliburton" },
  // ─── 美股（不動產）─────────────────────────────────────
  { ticker: "AMT",   name: "American Tower" },
  { ticker: "PLD",   name: "Prologis" },
  { ticker: "CCI",   name: "Crown Castle" },
  { ticker: "EQIX",  name: "Equinix" },
  { ticker: "SPG",   name: "Simon Property Group" },
  { ticker: "PSA",   name: "Public Storage" },
  { ticker: "O",     name: "Realty Income" },
  { ticker: "DLR",   name: "Digital Realty" },
  { ticker: "WELL",  name: "Welltower" },
  { ticker: "AVB",   name: "AvalonBay" },

  // ─── 韓國 KOSPI 50 主要成分股 ─────────────────────────
  { ticker: "005930.KS", name: "Samsung" },
  { ticker: "000660.KS", name: "SK Hynix" },
  { ticker: "005935.KS", name: "Samsung Electronics Pref" },
  { ticker: "005380.KS", name: "Hyundai Motor" },
  { ticker: "000270.KS", name: "Kia" },
  { ticker: "051910.KS", name: "LG Chem" },
  { ticker: "006400.KS", name: "Samsung SDI" },
  { ticker: "035420.KS", name: "Naver" },
  { ticker: "035720.KS", name: "Kakao" },
  { ticker: "068270.KS", name: "Celltrion" },
  { ticker: "105560.KS", name: "KB Financial" },
  { ticker: "055550.KS", name: "Shinhan Financial" },
  { ticker: "086790.KS", name: "Hana Financial" },
  { ticker: "316140.KS", name: "Woori Financial" },
  { ticker: "003670.KS", name: "Posco Holdings" },
  { ticker: "034730.KS", name: "SK" },
  { ticker: "017670.KS", name: "SK Telecom" },
  { ticker: "030200.KS", name: "KT" },
  { ticker: "032830.KS", name: "Samsung Life" },
  { ticker: "066570.KS", name: "LG Electronics" },
  { ticker: "003550.KS", name: "LG" },
  { ticker: "373220.KS", name: "LG Energy Solution" },
  { ticker: "012330.KS", name: "Hyundai Mobis" },
  { ticker: "009150.KS", name: "SEMCO", aliases: ["Samsung Electro-Mechanics", "三星電機"] },
  { ticker: "028260.KS", name: "Samsung C&T" },
  { ticker: "034020.KS", name: "Doosan Enerbility" },
  { ticker: "010130.KS", name: "Korea Zinc" },
  { ticker: "010950.KS", name: "S-Oil" },
  { ticker: "096770.KS", name: "SK Innovation" },
  { ticker: "011200.KS", name: "HMM" },
  { ticker: "036570.KS", name: "NCsoft" },
  { ticker: "259960.KS", name: "Krafton" },
  { ticker: "018260.KS", name: "Samsung SDS" },
  { ticker: "352820.KS", name: "Hybe" },
  { ticker: "011170.KS", name: "Lotte Chemical" },
  { ticker: "047050.KS", name: "Posco International" },
  { ticker: "402340.KS", name: "SK Square" },
  { ticker: "003490.KS", name: "Korean Air" },
  { ticker: "000810.KS", name: "Samsung Fire & Marine" },

  // ─── 中國 A 股（補充）──────────────────────────────────
  { ticker: "688183.SS", name: "生益電子" },
  { ticker: "300395.SZ", name: "菲利華" },

  // ─── 日本 Nikkei 225 主要成分股 ────────────────────────
  { ticker: "7203.T", name: "Toyota Motor" },
  { ticker: "6758.T", name: "Sony Group" },
  { ticker: "6861.T", name: "Keyence" },
  { ticker: "8306.T", name: "MUFG" },
  { ticker: "9432.T", name: "NTT" },
  { ticker: "9984.T", name: "SoftBank Group" },
  { ticker: "6501.T", name: "Hitachi" },
  { ticker: "8035.T", name: "Tokyo Electron" },
  { ticker: "4063.T", name: "Shin-Etsu Chemical" },
  { ticker: "6902.T", name: "Denso" },
  { ticker: "7741.T", name: "HOYA" },
  { ticker: "4519.T", name: "Chugai Pharmaceutical" },
  { ticker: "6098.T", name: "Recruit Holdings" },
  { ticker: "7267.T", name: "Honda Motor" },
  { ticker: "6954.T", name: "Fanuc" },
  { ticker: "4568.T", name: "Daiichi Sankyo" },
  { ticker: "6857.T", name: "Advantest" },
  { ticker: "9433.T", name: "KDDI" },
  { ticker: "8058.T", name: "Mitsubishi Corp" },
  { ticker: "8031.T", name: "Mitsui & Co" },
  { ticker: "9983.T", name: "Fast Retailing" },
  { ticker: "4502.T", name: "Takeda Pharmaceutical" },
  { ticker: "7974.T", name: "Nintendo" },
  { ticker: "6723.T", name: "Renesas Electronics" },
  { ticker: "6762.T", name: "TDK" },
  { ticker: "6981.T", name: "Murata" },
  { ticker: "9069.T", name: "SENKO" },
  { ticker: "4062.T", name: "Ibiden" },
  { ticker: "7751.T", name: "Canon" },
  { ticker: "6367.T", name: "Daikin Industries" },
  { ticker: "6971.T", name: "Kyocera" },
  { ticker: "3382.T", name: "Seven & i Holdings" },
  { ticker: "2914.T", name: "Japan Tobacco" },
  { ticker: "4661.T", name: "Oriental Land" },
  { ticker: "5108.T", name: "Bridgestone" },
  { ticker: "7269.T", name: "Suzuki Motor" },
  { ticker: "7270.T", name: "Subaru" },
  { ticker: "2802.T", name: "Ajinomoto",  aliases: ["味之素"] },
  { ticker: "4901.T", name: "Fujifilm" },
  { ticker: "6301.T", name: "Komatsu" },
  { ticker: "6594.T", name: "Nidec" },
  { ticker: "7832.T", name: "Bandai Namco" },
  { ticker: "9434.T", name: "SoftBank Corp" },
  { ticker: "4543.T", name: "Terumo" },
  { ticker: "9613.T", name: "NTT Data" },
  { ticker: "6503.T", name: "Mitsubishi Electric" },
  { ticker: "7011.T", name: "Mitsubishi Heavy Industries" },
  { ticker: "8001.T", name: "Itochu" },
  { ticker: "8002.T", name: "Marubeni" },
  { ticker: "6146.T", name: "Disco" },
  { ticker: "6920.T", name: "Lasertec" },
  { ticker: "6526.T", name: "Socionext" },
  { ticker: "4755.T", name: "Rakuten Group" },
  { ticker: "6752.T", name: "Panasonic" },
  { ticker: "2413.T", name: "M3" },
  { ticker: "4307.T", name: "Nomura Research Institute" },
  { ticker: "6273.T", name: "SMC" },
  { ticker: "7735.T", name: "Screen Holdings" },
  { ticker: "5201.T", name: "AGC" },
  { ticker: "7733.T", name: "Olympus" },
  { ticker: "8766.T", name: "Tokio Marine" },
  { ticker: "8411.T", name: "Mizuho Financial" },
  { ticker: "8316.T", name: "SMFG" },
  { ticker: "8053.T", name: "Sumitomo" },
];

export function lookupStock(query: string): { ticker: string; stock_name: string } | null {
  const q = query.trim(); if (!q) return null;
  const ql = q.toLowerCase();
  for (const s of scanStocks) {
    if (s.ticker.toLowerCase() === ql) return { ticker: s.ticker, stock_name: s.name };
    if (s.name === q) return { ticker: s.ticker, stock_name: s.name };
    if (s.aliases?.some(a => a.toLowerCase() === ql)) return { ticker: s.ticker, stock_name: s.name };
  }
  return null;
}
